using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.ServiceModel;
using System.ServiceModel.Channels;
using System.Threading.Tasks;
using System.Xml.Schema;
using System.Xml.Serialization;

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Catl.WebServices.AssembleAndCollectDataForSfc
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     此代码由工具生成。
    //     运行时版本:4.0.30319.42000
    //
    //     对此文件的更改可能会导致不正确的行为，并且如果
    //     重新生成代码，这些更改将会丢失。
    // </auto-generated>
    //------------------------------------------------------------------------------



    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [ServiceContract(Namespace = "http://machineintegration.ws.atlmes.com/", ConfigurationName = "MiAssembleAndCollectDataForSfcService")]
    public interface MiAssembleAndCollectDataForSfcService
    {

        // CODEGEN: 操作 miAssmebleAndCollectDataForSfc 以后生成的消息协定不是 RPC，也不是换行文档。
        [OperationContract(Action = "", ReplyAction = "*")]
        [XmlSerializerFormat()]
        [ServiceKnownType(typeof(AttributeValue))]
        miAssmebleAndCollectDataForSfcResponse1 miAssmebleAndCollectDataForSfc(miAssmebleAndCollectDataForSfcRequest request);

        [OperationContract(Action = "", ReplyAction = "*")]
        Task<miAssmebleAndCollectDataForSfcResponse1> miAssmebleAndCollectDataForSfcAsync(miAssmebleAndCollectDataForSfcRequest request);

        // CODEGEN: 操作 getInventoryQty 以后生成的消息协定不是 RPC，也不是换行文档。
        [OperationContract(Action = "", ReplyAction = "*")]
        [XmlSerializerFormat()]
        [ServiceKnownType(typeof(AttributeValue))]
        getInventoryQtyResponse1 getInventoryQty(getInventoryQtyRequest1 request);

        [OperationContract(Action = "", ReplyAction = "*")]
        Task<getInventoryQtyResponse1> getInventoryQtyAsync(getInventoryQtyRequest1 request);
    }

    /// <remarks/>
    [GeneratedCode("svcutil", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://machineintegration.ws.atlmes.com/")]
    public partial class miAssmebleAndCollectDataForSfc
    {

        private assembleAndCollectDataForSfcRequest assembleAndCollectDataForSfcRequestField;

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 0)]
        public assembleAndCollectDataForSfcRequest AssembleAndCollectDataForSfcRequest
        {
            get
            {
                return this.assembleAndCollectDataForSfcRequestField;
            }
            set
            {
                this.assembleAndCollectDataForSfcRequestField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("svcutil", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://machineintegration.ws.atlmes.com/")]
    public partial class assembleAndCollectDataForSfcRequest
    {

        private string siteField;

        private string sfcField;

        private string dcGroupField;

        private string dcGroupRevisionField;

        private string operationField;

        private string operationRevisionField;

        private string resourceField;

        private string userField;

        private string activityIdField;

        private dataCollectForSfcModeProcessSfc modeProcessSFCField;

        private bool partialAssemblyField;

        private miInventoryData[] inventoryArrayField;

        private machineIntegrationParametricData[] parametricDataArrayField;

        private nonConfirmCodeArray[] ncCodeArrayField;

        private string remarkField;

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 0)]
        public string site
        {
            get
            {
                return this.siteField;
            }
            set
            {
                this.siteField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 1)]
        public string sfc
        {
            get
            {
                return this.sfcField;
            }
            set
            {
                this.sfcField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 2)]
        public string dcGroup
        {
            get
            {
                return this.dcGroupField;
            }
            set
            {
                this.dcGroupField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 3)]
        public string dcGroupRevision
        {
            get
            {
                return this.dcGroupRevisionField;
            }
            set
            {
                this.dcGroupRevisionField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 4)]
        public string operation
        {
            get
            {
                return this.operationField;
            }
            set
            {
                this.operationField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 5)]
        public string operationRevision
        {
            get
            {
                return this.operationRevisionField;
            }
            set
            {
                this.operationRevisionField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 6)]
        public string resource
        {
            get
            {
                return this.resourceField;
            }
            set
            {
                this.resourceField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 7)]
        public string user
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 8)]
        public string activityId
        {
            get
            {
                return this.activityIdField;
            }
            set
            {
                this.activityIdField = value;
            }
        }

        [JsonConverter(typeof(StringEnumConverter))]
        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 9)]
        public dataCollectForSfcModeProcessSfc modeProcessSFC
        {
            get
            {
                return this.modeProcessSFCField;
            }
            set
            {
                this.modeProcessSFCField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 10)]
        public bool partialAssembly
        {
            get
            {
                return this.partialAssemblyField;
            }
            set
            {
                this.partialAssemblyField = value;
            }
        }

        /// <remarks/>
        [XmlElement("inventoryArray", Form = XmlSchemaForm.Unqualified, Order = 11)]
        public miInventoryData[] inventoryArray
        {
            get
            {
                return this.inventoryArrayField;
            }
            set
            {
                this.inventoryArrayField = value;
            }
        }

        /// <remarks/>
        [XmlElement("parametricDataArray", Form = XmlSchemaForm.Unqualified, Order = 12)]
        public machineIntegrationParametricData[] parametricDataArray
        {
            get
            {
                return this.parametricDataArrayField;
            }
            set
            {
                this.parametricDataArrayField = value;
            }
        }

        /// <remarks/>
        [XmlElement("ncCodeArray", Form = XmlSchemaForm.Unqualified, Order = 13)]
        public nonConfirmCodeArray[] ncCodeArray
        {
            get
            {
                return this.ncCodeArrayField;
            }
            set
            {
                this.ncCodeArrayField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 14)]
        public string remark
        {
            get
            {
                return this.remarkField;
            }
            set
            {
                this.remarkField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("svcutil", "4.8.3928.0")]
    [Serializable()]
    [XmlType(Namespace = "http://machineintegration.ws.atlmes.com/")]
    public enum dataCollectForSfcModeProcessSfc
    {

        /// <remarks/>
        MODE_NONE,

        /// <remarks/>
        MODE_START_SFC_PRE_DC,

        /// <remarks/>
        MODE_COMPLETE_SFC_POST_DC,

        /// <remarks/>
        MODE_PASS_SFC_POST_DC,

        /// <remarks/>
        MODE_REMOVE_PROCESSLOT_COMPLETE_SFC_POST_DC,

        /// <remarks/>
        MODE_START_AND_COMPLETE_SFC_POST_DC,
    }

    /// <remarks/>
    [GeneratedCode("svcutil", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://machineintegration.ws.atlmes.com/")]
    public partial class miInventoryData
    {

        private string inventoryField;

        private string qtyField;

        private AssemblyDataField[] assemblyDataFieldsField;

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 0)]
        public string inventory
        {
            get
            {
                return this.inventoryField;
            }
            set
            {
                this.inventoryField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 1)]
        public string qty
        {
            get
            {
                return this.qtyField;
            }
            set
            {
                this.qtyField = value;
            }
        }

        /// <remarks/>
        [XmlElement("assemblyDataFields", Form = XmlSchemaForm.Unqualified, Order = 2)]
        public AssemblyDataField[] assemblyDataFields
        {
            get
            {
                return this.assemblyDataFieldsField;
            }
            set
            {
                this.assemblyDataFieldsField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("svcutil", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://www.sap.com/me/production")]
    public partial class AssemblyDataField : AttributeValue
    {

        private decimal sequenceField;

        private bool sequenceFieldSpecified;

        /// <remarks/>
        [XmlElement(Order = 0)]
        public decimal sequence
        {
            get
            {
                return this.sequenceField;
            }
            set
            {
                this.sequenceField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool sequenceSpecified
        {
            get
            {
                return this.sequenceFieldSpecified;
            }
            set
            {
                this.sequenceFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [XmlInclude(typeof(AssemblyDataField))]
    [GeneratedCode("svcutil", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://www.sap.com/me/common")]
    public partial class AttributeValue
    {

        private string attributeField;

        private string valueField;

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 0)]
        public string attribute
        {
            get
            {
                return this.attributeField;
            }
            set
            {
                this.attributeField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("svcutil", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://machineintegration.ws.atlmes.com/")]
    public partial class baseResponse
    {

        private int codeField;

        private bool codeFieldSpecified;

        private string messageField;

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 0)]
        public int code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool codeSpecified
        {
            get
            {
                return this.codeFieldSpecified;
            }
            set
            {
                this.codeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 1)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("svcutil", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://machineintegration.ws.atlmes.com/")]
    public partial class getInventoryQtyResponse
    {

        private baseResponse returnField;

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 0)]
        public baseResponse @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("svcutil", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://machineintegration.ws.atlmes.com/")]
    public partial class getInventoryQtyRequest
    {

        private string siteField;

        private string inventoryField;

        private string resourceField;

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 0)]
        public string site
        {
            get
            {
                return this.siteField;
            }
            set
            {
                this.siteField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 1)]
        public string inventory
        {
            get
            {
                return this.inventoryField;
            }
            set
            {
                this.inventoryField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 2)]
        public string resource
        {
            get
            {
                return this.resourceField;
            }
            set
            {
                this.resourceField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("svcutil", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://machineintegration.ws.atlmes.com/")]
    public partial class getInventoryQty
    {

        private getInventoryQtyRequest getInventoryQtyRequestField;

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 0)]
        public getInventoryQtyRequest GetInventoryQtyRequest
        {
            get
            {
                return this.getInventoryQtyRequestField;
            }
            set
            {
                this.getInventoryQtyRequestField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("svcutil", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://machineintegration.ws.atlmes.com/")]
    public partial class assembleAndCollectDataForSfcResponse
    {

        private int codeField;

        private string messageField;

        private string sfcField;

        private string failedInventoryField;

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 0)]
        public int code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 1)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 2)]
        public string sfc
        {
            get
            {
                return this.sfcField;
            }
            set
            {
                this.sfcField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 3)]
        public string failedInventory
        {
            get
            {
                return this.failedInventoryField;
            }
            set
            {
                this.failedInventoryField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("svcutil", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://machineintegration.ws.atlmes.com/")]
    public partial class miAssmebleAndCollectDataForSfcResponse
    {

        private assembleAndCollectDataForSfcResponse returnField;

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 0)]
        public assembleAndCollectDataForSfcResponse @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("svcutil", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://machineintegration.ws.atlmes.com/")]
    public partial class nonConfirmCodeArray
    {

        private string ncCodeField;

        private bool hasNcField;

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 0)]
        public string ncCode
        {
            get
            {
                return this.ncCodeField;
            }
            set
            {
                this.ncCodeField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 1)]
        public bool hasNc
        {
            get
            {
                return this.hasNcField;
            }
            set
            {
                this.hasNcField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("svcutil", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://machineintegration.ws.atlmes.com/")]
    public partial class machineIntegrationParametricData
    {

        private string nameField;

        private string valueField;

        private ParameterDataType dataTypeField;

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        [JsonConverter(typeof(StringEnumConverter))]
        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 2)]
        public ParameterDataType dataType
        {
            get
            {
                return this.dataTypeField;
            }
            set
            {
                this.dataTypeField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("svcutil", "4.8.3928.0")]
    [Serializable()]
    [XmlType(Namespace = "http://www.sap.com/me/datacollection")]
    public enum ParameterDataType
    {

        /// <remarks/>
        NUMBER,

        /// <remarks/>
        TEXT,

        /// <remarks/>
        FORMULA,

        /// <remarks/>
        BOOLEAN,
    }

    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    [MessageContract(IsWrapped = false)]
    public partial class miAssmebleAndCollectDataForSfcRequest
    {

        [MessageBodyMember(Namespace = "http://machineintegration.ws.atlmes.com/", Order = 0)]
        public miAssmebleAndCollectDataForSfc miAssmebleAndCollectDataForSfc;

        public miAssmebleAndCollectDataForSfcRequest()
        {
        }

        public miAssmebleAndCollectDataForSfcRequest(miAssmebleAndCollectDataForSfc miAssmebleAndCollectDataForSfc)
        {
            this.miAssmebleAndCollectDataForSfc = miAssmebleAndCollectDataForSfc;
        }
    }

    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    [MessageContract(IsWrapped = false)]
    public partial class miAssmebleAndCollectDataForSfcResponse1
    {

        [MessageBodyMember(Namespace = "http://machineintegration.ws.atlmes.com/", Order = 0)]
        public miAssmebleAndCollectDataForSfcResponse miAssmebleAndCollectDataForSfcResponse;

        public miAssmebleAndCollectDataForSfcResponse1()
        {
        }

        public miAssmebleAndCollectDataForSfcResponse1(miAssmebleAndCollectDataForSfcResponse miAssmebleAndCollectDataForSfcResponse)
        {
            this.miAssmebleAndCollectDataForSfcResponse = miAssmebleAndCollectDataForSfcResponse;
        }
    }

    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    [MessageContract(IsWrapped = false)]
    public partial class getInventoryQtyRequest1
    {

        [MessageBodyMember(Namespace = "http://machineintegration.ws.atlmes.com/", Order = 0)]
        public getInventoryQty getInventoryQty;

        public getInventoryQtyRequest1()
        {
        }

        public getInventoryQtyRequest1(getInventoryQty getInventoryQty)
        {
            this.getInventoryQty = getInventoryQty;
        }
    }

    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    [MessageContract(IsWrapped = false)]
    public partial class getInventoryQtyResponse1
    {

        [MessageBodyMember(Namespace = "http://machineintegration.ws.atlmes.com/", Order = 0)]
        public getInventoryQtyResponse getInventoryQtyResponse;

        public getInventoryQtyResponse1()
        {
        }

        public getInventoryQtyResponse1(getInventoryQtyResponse getInventoryQtyResponse)
        {
            this.getInventoryQtyResponse = getInventoryQtyResponse;
        }
    }

    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public interface MiAssembleAndCollectDataForSfcServiceChannel : MiAssembleAndCollectDataForSfcService, IClientChannel
    {
    }

    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public partial class MiAssembleAndCollectDataForSfcServiceClient : ClientBase<MiAssembleAndCollectDataForSfcService>, MiAssembleAndCollectDataForSfcService
    {

        public MiAssembleAndCollectDataForSfcServiceClient()
        {
        }

        public MiAssembleAndCollectDataForSfcServiceClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public MiAssembleAndCollectDataForSfcServiceClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public MiAssembleAndCollectDataForSfcServiceClient(string endpointConfigurationName, EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public MiAssembleAndCollectDataForSfcServiceClient(Binding binding, EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        miAssmebleAndCollectDataForSfcResponse1 MiAssembleAndCollectDataForSfcService.miAssmebleAndCollectDataForSfc(miAssmebleAndCollectDataForSfcRequest request)
        {
            return base.Channel.miAssmebleAndCollectDataForSfc(request);
        }

        public miAssmebleAndCollectDataForSfcResponse miAssmebleAndCollectDataForSfc(miAssmebleAndCollectDataForSfc miAssmebleAndCollectDataForSfc1)
        {
            miAssmebleAndCollectDataForSfcRequest inValue = new miAssmebleAndCollectDataForSfcRequest();
            inValue.miAssmebleAndCollectDataForSfc = miAssmebleAndCollectDataForSfc1;
            miAssmebleAndCollectDataForSfcResponse1 retVal = ((MiAssembleAndCollectDataForSfcService)(this)).miAssmebleAndCollectDataForSfc(inValue);
            return retVal.miAssmebleAndCollectDataForSfcResponse;
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        Task<miAssmebleAndCollectDataForSfcResponse1> MiAssembleAndCollectDataForSfcService.miAssmebleAndCollectDataForSfcAsync(miAssmebleAndCollectDataForSfcRequest request)
        {
            return base.Channel.miAssmebleAndCollectDataForSfcAsync(request);
        }

        public Task<miAssmebleAndCollectDataForSfcResponse1> miAssmebleAndCollectDataForSfcAsync(miAssmebleAndCollectDataForSfc miAssmebleAndCollectDataForSfc)
        {
            miAssmebleAndCollectDataForSfcRequest inValue = new miAssmebleAndCollectDataForSfcRequest();
            inValue.miAssmebleAndCollectDataForSfc = miAssmebleAndCollectDataForSfc;
            return ((MiAssembleAndCollectDataForSfcService)(this)).miAssmebleAndCollectDataForSfcAsync(inValue);
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        getInventoryQtyResponse1 MiAssembleAndCollectDataForSfcService.getInventoryQty(getInventoryQtyRequest1 request)
        {
            return base.Channel.getInventoryQty(request);
        }

        public getInventoryQtyResponse getInventoryQty(getInventoryQty getInventoryQty1)
        {
            getInventoryQtyRequest1 inValue = new getInventoryQtyRequest1();
            inValue.getInventoryQty = getInventoryQty1;
            getInventoryQtyResponse1 retVal = ((MiAssembleAndCollectDataForSfcService)(this)).getInventoryQty(inValue);
            return retVal.getInventoryQtyResponse;
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        Task<getInventoryQtyResponse1> MiAssembleAndCollectDataForSfcService.getInventoryQtyAsync(getInventoryQtyRequest1 request)
        {
            return base.Channel.getInventoryQtyAsync(request);
        }

        public Task<getInventoryQtyResponse1> getInventoryQtyAsync(getInventoryQty getInventoryQty)
        {
            getInventoryQtyRequest1 inValue = new getInventoryQtyRequest1();
            inValue.getInventoryQty = getInventoryQty;
            return ((MiAssembleAndCollectDataForSfcService)(this)).getInventoryQtyAsync(inValue);
        }
    }
}
