using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.ServiceModel;
using System.ServiceModel.Channels;
using System.ServiceModel.Description;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Schema;
using System.Xml.Serialization;

namespace Catl.WebServices.MICheckInventoryAttribute
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     此代码由工具生成。
    //
    //     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
    //     代码重新生成。
    // </auto-generated>
    //------------------------------------------------------------------------------



    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace = "http://machineintegration.ws.atlmes.com/")]
    public partial class BusinessException
    {

        private object[] detailsField;

        private int errorCodeField;

        private string messageField;

        private stackTraceElement[][] suppressedField;

        /// <remarks/>
        [XmlElement("details", Form = XmlSchemaForm.Unqualified, Order = 0)]
        public object[] details
        {
            get
            {
                return this.detailsField;
            }
            set
            {
                this.detailsField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 1)]
        public int errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 2)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        [XmlArray(Form = XmlSchemaForm.Unqualified, Order = 3)]
        [XmlArrayItem("stackTrace", typeof(stackTraceElement[]), Form = XmlSchemaForm.Unqualified)]
        public stackTraceElement[][] suppressed
        {
            get
            {
                return this.suppressedField;
            }
            set
            {
                this.suppressedField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace = "http://machineintegration.ws.atlmes.com/")]
    public partial class getInventoryIDDataFieldResponse
    {

        private string returnField;

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 0)]
        public string @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace = "http://machineintegration.ws.atlmes.com/")]
    public partial class getInventoryIDDataField
    {

        private string arg0Field;

        private string arg1Field;

        private string arg2Field;

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 0)]
        public string arg0
        {
            get
            {
                return this.arg0Field;
            }
            set
            {
                this.arg0Field = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 1)]
        public string arg1
        {
            get
            {
                return this.arg1Field;
            }
            set
            {
                this.arg1Field = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 2)]
        public string arg2
        {
            get
            {
                return this.arg2Field;
            }
            set
            {
                this.arg2Field = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace = "http://machineintegration.ws.atlmes.com/")]
    public partial class stackTraceElement
    {
    }

    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace = "http://machineintegration.ws.atlmes.com/")]
    public partial class getNcListByInventoryID
    {

        private string arg0Field;

        private string arg1Field;

        private string arg2Field;

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 0)]
        public string arg0
        {
            get
            {
                return this.arg0Field;
            }
            set
            {
                this.arg0Field = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 1)]
        public string arg1
        {
            get
            {
                return this.arg1Field;
            }
            set
            {
                this.arg1Field = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 2)]
        public string arg2
        {
            get
            {
                return this.arg2Field;
            }
            set
            {
                this.arg2Field = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace = "http://machineintegration.ws.atlmes.com/")]
    public partial class checkInventoryDataFields
    {

        private string inventoryField;

        private string attributeField;

        private string valueField;

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 0)]
        public string inventory
        {
            get
            {
                return this.inventoryField;
            }
            set
            {
                this.inventoryField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 1)]
        public string attribute
        {
            get
            {
                return this.attributeField;
            }
            set
            {
                this.attributeField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 2)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace = "http://machineintegration.ws.atlmes.com/")]
    public partial class checkInventoryAttributesResponse
    {

        private int codeField;

        private string messageField;

        private string failedSfcField;

        private string failedInventoryField;

        private checkInventoryDataFields[] inventoryDataFieldsField;

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 0)]
        public int code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 1)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 2)]
        public string failedSfc
        {
            get
            {
                return this.failedSfcField;
            }
            set
            {
                this.failedSfcField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 3)]
        public string failedInventory
        {
            get
            {
                return this.failedInventoryField;
            }
            set
            {
                this.failedInventoryField = value;
            }
        }

        /// <remarks/>
        [XmlElement("inventoryDataFields", Form = XmlSchemaForm.Unqualified, IsNullable = true, Order = 4)]
        public checkInventoryDataFields[] inventoryDataFields
        {
            get
            {
                return this.inventoryDataFieldsField;
            }
            set
            {
                this.inventoryDataFieldsField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace = "http://machineintegration.ws.atlmes.com/")]
    public partial class miCheckInventoryAttributesResponse
    {

        private checkInventoryAttributesResponse returnField;

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 0)]
        public checkInventoryAttributesResponse @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace = "http://machineintegration.ws.atlmes.com/")]
    public partial class ModuleCellMarkingOrTimeCheckRequest
    {

        private string siteField;

        private string sfcField;

        private string operationField;

        private string operationRevisionField;

        private string resourceField;

        private string userField;

        private string activityIdField;

        private modeCheckInventory modeCheckInventoryField;

        private int requiredQuantityField;

        private string[] inventoryArrayField;

        private string[] inventoryAttributeListField;

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 0)]
        public string site
        {
            get
            {
                return this.siteField;
            }
            set
            {
                this.siteField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 1)]
        public string sfc
        {
            get
            {
                return this.sfcField;
            }
            set
            {
                this.sfcField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 2)]
        public string operation
        {
            get
            {
                return this.operationField;
            }
            set
            {
                this.operationField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 3)]
        public string operationRevision
        {
            get
            {
                return this.operationRevisionField;
            }
            set
            {
                this.operationRevisionField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 4)]
        public string resource
        {
            get
            {
                return this.resourceField;
            }
            set
            {
                this.resourceField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 5)]
        public string user
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 6)]
        public string activityId
        {
            get
            {
                return this.activityIdField;
            }
            set
            {
                this.activityIdField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 7)]
        public modeCheckInventory modeCheckInventory
        {
            get
            {
                return this.modeCheckInventoryField;
            }
            set
            {
                this.modeCheckInventoryField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 8)]
        public int requiredQuantity
        {
            get
            {
                return this.requiredQuantityField;
            }
            set
            {
                this.requiredQuantityField = value;
            }
        }

        /// <remarks/>
        [XmlElement("inventoryArray", Form = XmlSchemaForm.Unqualified, Order = 9)]
        public string[] inventoryArray
        {
            get
            {
                return this.inventoryArrayField;
            }
            set
            {
                this.inventoryArrayField = value;
            }
        }

        /// <remarks/>
        [XmlElement("inventoryAttributeList", Form = XmlSchemaForm.Unqualified, Order = 10)]
        public string[] inventoryAttributeList
        {
            get
            {
                return this.inventoryAttributeListField;
            }
            set
            {
                this.inventoryAttributeListField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [XmlType(Namespace = "http://machineintegration.ws.atlmes.com/")]
    public enum modeCheckInventory
    {

        /// <remarks/>
        MODE_MARK_ONLY,

        /// <remarks/>
        MODE_TIME_ONLY,

        /// <remarks/>
        MODE_MARK_AND_TIME,

        /// <remarks/>
        MODE_NONE,
    }

    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace = "http://machineintegration.ws.atlmes.com/")]
    public partial class miCheckInventoryAttributes
    {

        private ModuleCellMarkingOrTimeCheckRequest checkInventoryAttributesRequestField;

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 0)]
        public ModuleCellMarkingOrTimeCheckRequest CheckInventoryAttributesRequest
        {
            get
            {
                return this.checkInventoryAttributesRequestField;
            }
            set
            {
                this.checkInventoryAttributesRequestField = value;
            }
        }
    }

    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [ServiceContract(Namespace = "http://machineintegration.ws.atlmes.com/", ConfigurationName = "MiCheckInventoryAttributesService")]
    public interface MiCheckInventoryAttributesService
    {

        [OperationContract(Action = "", ReplyAction = "*")]
        [XmlSerializerFormat(SupportFaults = true)]
        [ServiceKnownType(typeof(getInventoryIDDataFieldResponse))]
        [ServiceKnownType(typeof(getInventoryIDDataField))]
        Task<miCheckInventoryAttributesResponse1> miCheckInventoryAttributesAsync(miCheckInventoryAttributesRequest request);

        [OperationContract(Action = "", ReplyAction = "*")]
        [FaultContract(typeof(BusinessException), Action = "", Name = "BusinessException")]
        [XmlSerializerFormat(SupportFaults = true)]
        [ServiceKnownType(typeof(getInventoryIDDataFieldResponse))]
        [ServiceKnownType(typeof(getInventoryIDDataField))]
        Task<getNcListByInventoryIDResponse> getNcListByInventoryIDAsync(getNcListByInventoryIDRequest request);

        [OperationContract(Action = "", ReplyAction = "*")]
        [FaultContract(typeof(BusinessException), Action = "", Name = "BusinessException")]
        [XmlSerializerFormat(SupportFaults = true)]
        [ServiceKnownType(typeof(getInventoryIDDataFieldResponse))]
        [ServiceKnownType(typeof(getInventoryIDDataField))]
        Task<getInventoryIDDataFieldResponse1> getInventoryIDDataFieldAsync(getInventoryIDDataFieldRequest request);
    }

    [DebuggerStepThrough()]
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    [MessageContract(IsWrapped = false)]
    public partial class miCheckInventoryAttributesRequest
    {

        [MessageBodyMember(Namespace = "http://machineintegration.ws.atlmes.com/", Order = 0)]
        public miCheckInventoryAttributes miCheckInventoryAttributes;

        public miCheckInventoryAttributesRequest()
        {
        }

        public miCheckInventoryAttributesRequest(miCheckInventoryAttributes miCheckInventoryAttributes)
        {
            this.miCheckInventoryAttributes = miCheckInventoryAttributes;
        }
    }

    [DebuggerStepThrough()]
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    [MessageContract(IsWrapped = false)]
    public partial class miCheckInventoryAttributesResponse1
    {

        [MessageBodyMember(Namespace = "http://machineintegration.ws.atlmes.com/", Order = 0)]
        public miCheckInventoryAttributesResponse miCheckInventoryAttributesResponse;

        public miCheckInventoryAttributesResponse1()
        {
        }

        public miCheckInventoryAttributesResponse1(miCheckInventoryAttributesResponse miCheckInventoryAttributesResponse)
        {
            this.miCheckInventoryAttributesResponse = miCheckInventoryAttributesResponse;
        }
    }

    [DebuggerStepThrough()]
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    [MessageContract(IsWrapped = false)]
    public partial class getNcListByInventoryIDRequest
    {

        [MessageBodyMember(Namespace = "http://machineintegration.ws.atlmes.com/", Order = 0)]
        public getNcListByInventoryID getNcListByInventoryID;

        public getNcListByInventoryIDRequest()
        {
        }

        public getNcListByInventoryIDRequest(getNcListByInventoryID getNcListByInventoryID)
        {
            this.getNcListByInventoryID = getNcListByInventoryID;
        }
    }

    [DebuggerStepThrough()]
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    [MessageContract(IsWrapped = false)]
    public partial class getNcListByInventoryIDResponse
    {

        [MessageBodyMember(Name = "getNcListByInventoryIDResponse", Namespace = "http://machineintegration.ws.atlmes.com/", Order = 0)]
        [XmlArrayItem("return", Form = XmlSchemaForm.Unqualified, IsNullable = false)]
        public string[] getNcListByInventoryIDResponse1;

        public getNcListByInventoryIDResponse()
        {
        }

        public getNcListByInventoryIDResponse(string[] getNcListByInventoryIDResponse1)
        {
            this.getNcListByInventoryIDResponse1 = getNcListByInventoryIDResponse1;
        }
    }

    [DebuggerStepThrough()]
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    [MessageContract(IsWrapped = false)]
    public partial class getInventoryIDDataFieldRequest
    {

        [MessageBodyMember(Namespace = "http://machineintegration.ws.atlmes.com/", Order = 0)]
        public getInventoryIDDataField getInventoryIDDataField;

        public getInventoryIDDataFieldRequest()
        {
        }

        public getInventoryIDDataFieldRequest(getInventoryIDDataField getInventoryIDDataField)
        {
            this.getInventoryIDDataField = getInventoryIDDataField;
        }
    }

    [DebuggerStepThrough()]
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    [MessageContract(IsWrapped = false)]
    public partial class getInventoryIDDataFieldResponse1
    {

        [MessageBodyMember(Namespace = "http://machineintegration.ws.atlmes.com/", Order = 0)]
        public getInventoryIDDataFieldResponse getInventoryIDDataFieldResponse;

        public getInventoryIDDataFieldResponse1()
        {
        }

        public getInventoryIDDataFieldResponse1(getInventoryIDDataFieldResponse getInventoryIDDataFieldResponse)
        {
            this.getInventoryIDDataFieldResponse = getInventoryIDDataFieldResponse;
        }
    }

    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface MiCheckInventoryAttributesServiceChannel : MiCheckInventoryAttributesService, IClientChannel
    {
    }

    [DebuggerStepThrough()]
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class MiCheckInventoryAttributesServiceClient : ClientBase<MiCheckInventoryAttributesService>, MiCheckInventoryAttributesService
    {

        /// <summary>
        /// 实现此分部方法，配置服务终结点。
        /// </summary>
        /// <param name="serviceEndpoint">要配置的终结点</param>
        /// <param name="clientCredentials">客户端凭据</param>
        static partial void ConfigureEndpoint(ServiceEndpoint serviceEndpoint, ClientCredentials clientCredentials);

        public MiCheckInventoryAttributesServiceClient() :
                base(GetDefaultBinding(), GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.MiCheckInventoryAttributesServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public MiCheckInventoryAttributesServiceClient(EndpointConfiguration endpointConfiguration) :
                base(GetBindingForEndpoint(endpointConfiguration), GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public MiCheckInventoryAttributesServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(GetBindingForEndpoint(endpointConfiguration), new EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public MiCheckInventoryAttributesServiceClient(EndpointConfiguration endpointConfiguration, EndpointAddress remoteAddress) :
                base(GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public MiCheckInventoryAttributesServiceClient(Binding binding, EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        Task<miCheckInventoryAttributesResponse1> MiCheckInventoryAttributesService.miCheckInventoryAttributesAsync(miCheckInventoryAttributesRequest request)
        {
            return base.Channel.miCheckInventoryAttributesAsync(request);
        }

        public Task<miCheckInventoryAttributesResponse1> miCheckInventoryAttributesAsync(miCheckInventoryAttributes miCheckInventoryAttributes)
        {
            miCheckInventoryAttributesRequest inValue = new miCheckInventoryAttributesRequest();
            inValue.miCheckInventoryAttributes = miCheckInventoryAttributes;
            return ((MiCheckInventoryAttributesService)(this)).miCheckInventoryAttributesAsync(inValue);
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        Task<getNcListByInventoryIDResponse> MiCheckInventoryAttributesService.getNcListByInventoryIDAsync(getNcListByInventoryIDRequest request)
        {
            return base.Channel.getNcListByInventoryIDAsync(request);
        }

        public Task<getNcListByInventoryIDResponse> getNcListByInventoryIDAsync(getNcListByInventoryID getNcListByInventoryID)
        {
            getNcListByInventoryIDRequest inValue = new getNcListByInventoryIDRequest();
            inValue.getNcListByInventoryID = getNcListByInventoryID;
            return ((MiCheckInventoryAttributesService)(this)).getNcListByInventoryIDAsync(inValue);
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        Task<getInventoryIDDataFieldResponse1> MiCheckInventoryAttributesService.getInventoryIDDataFieldAsync(getInventoryIDDataFieldRequest request)
        {
            return base.Channel.getInventoryIDDataFieldAsync(request);
        }

        public Task<getInventoryIDDataFieldResponse1> getInventoryIDDataFieldAsync(getInventoryIDDataField getInventoryIDDataField)
        {
            getInventoryIDDataFieldRequest inValue = new getInventoryIDDataFieldRequest();
            inValue.getInventoryIDDataField = getInventoryIDDataField;
            return ((MiCheckInventoryAttributesService)(this)).getInventoryIDDataFieldAsync(inValue);
        }

        public virtual Task OpenAsync()
        {
            return Task.Factory.FromAsync(((ICommunicationObject)(this)).BeginOpen(null, null), new Action<IAsyncResult>(((ICommunicationObject)(this)).EndOpen));
        }

        public virtual Task CloseAsync()
        {
            return Task.Factory.FromAsync(((ICommunicationObject)(this)).BeginClose(null, null), new Action<IAsyncResult>(((ICommunicationObject)(this)).EndClose));
        }

        private static Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MiCheckInventoryAttributesServicePort))
            {
                BasicHttpBinding result = new BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }

        private static EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MiCheckInventoryAttributesServicePort))
            {
                return new EndpointAddress("http://rqmes1p023:50300/atlmeswebservice/MiCheckInventoryAttributesServiceService" +
                                           "");
            }
            throw new InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }

        private static Binding GetDefaultBinding()
        {
            return GetBindingForEndpoint(EndpointConfiguration.MiCheckInventoryAttributesServicePort);
        }

        private static EndpointAddress GetDefaultEndpointAddress()
        {
            return GetEndpointAddress(EndpointConfiguration.MiCheckInventoryAttributesServicePort);
        }

        public enum EndpointConfiguration
        {

            MiCheckInventoryAttributesServicePort,
        }
    }

}