using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.ServiceModel;
using System.ServiceModel.Channels;
using System.ServiceModel.Description;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Schema;
using System.Xml.Serialization;

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Catl.WebServices.DataCollectForResourceFAI
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     此代码由工具生成。
    //
    //     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
    //     代码重新生成。
    // </auto-generated>
    //------------------------------------------------------------------------------



    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace = "http://machine.ws.atlmes.com/")]
    public partial class BusinessException
    {

        private object[] detailsField;

        private int errorCodeField;

        private string messageField;

        /// <remarks/>
        [XmlElement("details", Form = XmlSchemaForm.Unqualified, Order = 0)]
        public object[] details
        {
            get
            {
                return this.detailsField;
            }
            set
            {
                this.detailsField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 1)]
        public int errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 2)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace = "http://machine.ws.atlmes.com/")]
    public partial class getCustomDataValueExResponse
    {

        private string returnField;

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 0)]
        public string @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace = "http://machine.ws.atlmes.com/")]
    public partial class getCustomDataValueEx
    {

        private string arg0Field;

        private ObjectAliasEnum arg1Field;

        private bool arg1FieldSpecified;

        private string arg2Field;

        private string arg3Field;

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 0)]
        public string arg0
        {
            get
            {
                return this.arg0Field;
            }
            set
            {
                this.arg0Field = value;
            }
        }
        [JsonConverter(typeof(StringEnumConverter))]

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 1)]
        public ObjectAliasEnum arg1
        {
            get
            {
                return this.arg1Field;
            }
            set
            {
                this.arg1Field = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool arg1Specified
        {
            get
            {
                return this.arg1FieldSpecified;
            }
            set
            {
                this.arg1FieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 2)]
        public string arg2
        {
            get
            {
                return this.arg2Field;
            }
            set
            {
                this.arg2Field = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 3)]
        public string arg3
        {
            get
            {
                return this.arg3Field;
            }
            set
            {
                this.arg3Field = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [XmlType(Namespace = "http://www.sap.com/me/common")]
    public enum ObjectAliasEnum
    {

        /// <remarks/>
        ACTIVITY,

        /// <remarks/>
        ACTIVITY_GROUP,

        /// <remarks/>
        ACTIVITY_LOG,

        /// <remarks/>
        ALARM,

        /// <remarks/>
        ALARM_LOG,

        /// <remarks/>
        APPLICATION_SETTING,

        /// <remarks/>
        ATTACHMENT,

        /// <remarks/>
        ATTENDANCE_LOG,

        /// <remarks/>
        BACKGROUND_PROCESS,

        /// <remarks/>
        BOM,

        /// <remarks/>
        BOM_COMPONENT,

        /// <remarks/>
        BUYOFF,

        /// <remarks/>
        BUYOFF_LOG,

        /// <remarks/>
        CERTIFICATION,

        /// <remarks/>
        CNC_PROGRAM,

        /// <remarks/>
        CONTAINER,

        /// <remarks/>
        CONTAINER_DATA,

        /// <remarks/>
        COST_CENTER,

        /// <remarks/>
        CUSTOMER,

        /// <remarks/>
        DATA_FIELD,

        /// <remarks/>
        DATA_TYPE,

        /// <remarks/>
        DC_GROUP,

        /// <remarks/>
        DOCUMENT,

        /// <remarks/>
        INVENTORY,

        /// <remarks/>
        INVENTORY_LOG,

        /// <remarks/>
        ITEM_GROUP,

        /// <remarks/>
        LABOR_CHARGE_CODE,

        /// <remarks/>
        MESSAGE,

        /// <remarks/>
        MESSAGE_LOG,

        /// <remarks/>
        MESSAGE_TYPE,

        /// <remarks/>
        NC_CODE,

        /// <remarks/>
        NEXT_NUMBER,

        /// <remarks/>
        OPERATION,

        /// <remarks/>
        PROCESS_LOT,

        /// <remarks/>
        PRODUCTION_LOG,

        /// <remarks/>
        REASON_CODE,

        /// <remarks/>
        SAMPLE_PLAN,

        /// <remarks/>
        WORK_INSTRUCTION,

        /// <remarks/>
        ITEM,

        /// <remarks/>
        RESOURCE,

        /// <remarks/>
        ROUTER,

        /// <remarks/>
        SHOP_ORDER,

        /// <remarks/>
        ROUTER_STEP,

        /// <remarks/>
        ROUTER_OPERATION,

        /// <remarks/>
        SFC,

        /// <remarks/>
        USR,

        /// <remarks/>
        USER_GROUP,

        /// <remarks/>
        WORK_CENTER,

        /// <remarks/>
        WORKSTATION,

        /// <remarks/>
        RESOURCE_TYPE,

        /// <remarks/>
        CUSTOMER_ORDER,
    }

    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace = "http://machine.ws.atlmes.com/")]
    public partial class erroAvoidResponse
    {
    }

    /// <remarks/>
    [XmlInclude(typeof(abstractDataSource))]
    [XmlInclude(typeof(baseDataSource))]
    [XmlInclude(typeof(systemBase))]
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace = "http://machine.ws.atlmes.com/")]
    public partial class baseObject
    {
    }

    /// <remarks/>
    [XmlInclude(typeof(baseDataSource))]
    [XmlInclude(typeof(systemBase))]
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace = "http://machine.ws.atlmes.com/")]
    public abstract partial class abstractDataSource : baseObject
    {

        private string dataSourceNameField;

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 0)]
        public string dataSourceName
        {
            get
            {
                return this.dataSourceNameField;
            }
            set
            {
                this.dataSourceNameField = value;
            }
        }
    }

    /// <remarks/>
    [XmlInclude(typeof(systemBase))]
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace = "http://machine.ws.atlmes.com/")]
    public partial class baseDataSource : abstractDataSource
    {
    }

    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace = "http://machine.ws.atlmes.com/")]
    public partial class systemBase : baseDataSource
    {
    }

    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace = "http://machine.ws.atlmes.com/")]
    public partial class erroAvoid
    {

        private string arg0Field;

        private string arg1Field;

        private string arg2Field;

        private string arg3Field;

        private string arg4Field;

        private systemBase arg5Field;

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 0)]
        public string arg0
        {
            get
            {
                return this.arg0Field;
            }
            set
            {
                this.arg0Field = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 1)]
        public string arg1
        {
            get
            {
                return this.arg1Field;
            }
            set
            {
                this.arg1Field = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 2)]
        public string arg2
        {
            get
            {
                return this.arg2Field;
            }
            set
            {
                this.arg2Field = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 3)]
        public string arg3
        {
            get
            {
                return this.arg3Field;
            }
            set
            {
                this.arg3Field = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 4)]
        public string arg4
        {
            get
            {
                return this.arg4Field;
            }
            set
            {
                this.arg4Field = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 5)]
        public systemBase arg5
        {
            get
            {
                return this.arg5Field;
            }
            set
            {
                this.arg5Field = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace = "http://machine.ws.atlmes.com/")]
    public partial class machineIntegrationResourceDcResponse
    {

        private int codeField;

        private bool codeFieldSpecified;

        private string messageField;

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 0)]
        public int code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool codeSpecified
        {
            get
            {
                return this.codeFieldSpecified;
            }
            set
            {
                this.codeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 1)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace = "http://machine.ws.atlmes.com/")]
    public partial class dataCollectForResourceFAIResponse
    {

        private machineIntegrationResourceDcResponse returnField;

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 0)]
        public machineIntegrationResourceDcResponse @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace = "http://machine.ws.atlmes.com/")]
    public partial class machineIntegrationParametricData
    {

        private string nameField;

        private string valueField;

        private ParameterDataType dataTypeField;

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 2)]
        public ParameterDataType dataType
        {
            get
            {
                return this.dataTypeField;
            }
            set
            {
                this.dataTypeField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [XmlType(Namespace = "http://www.sap.com/me/datacollection")]
    public enum ParameterDataType
    {

        /// <remarks/>
        NUMBER,

        /// <remarks/>
        TEXT,

        /// <remarks/>
        FORMULA,

        /// <remarks/>
        BOOLEAN,
    }

    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace = "http://machine.ws.atlmes.com/")]
    public partial class dataCollectForResourceFAIRequest
    {

        private string siteField;

        private string dcGroupField;

        private string dcModeField;

        private string sfcField;

        private string materialField;

        private string materialRevisionField;

        private string dcGroupRevisionField;

        private string resourceField;

        private string operationField;

        private string operationRevisionField;

        private string dcGroupSequenceField;

        private string userField;

        private machineIntegrationParametricData[] parametricDataArrayField;

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 0)]
        public string site
        {
            get
            {
                return this.siteField;
            }
            set
            {
                this.siteField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 1)]
        public string dcGroup
        {
            get
            {
                return this.dcGroupField;
            }
            set
            {
                this.dcGroupField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 2)]
        public string dcMode
        {
            get
            {
                return this.dcModeField;
            }
            set
            {
                this.dcModeField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 3)]
        public string sfc
        {
            get
            {
                return this.sfcField;
            }
            set
            {
                this.sfcField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 4)]
        public string material
        {
            get
            {
                return this.materialField;
            }
            set
            {
                this.materialField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 5)]
        public string materialRevision
        {
            get
            {
                return this.materialRevisionField;
            }
            set
            {
                this.materialRevisionField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 6)]
        public string dcGroupRevision
        {
            get
            {
                return this.dcGroupRevisionField;
            }
            set
            {
                this.dcGroupRevisionField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 7)]
        public string resource
        {
            get
            {
                return this.resourceField;
            }
            set
            {
                this.resourceField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 8)]
        public string operation
        {
            get
            {
                return this.operationField;
            }
            set
            {
                this.operationField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 9)]
        public string operationRevision
        {
            get
            {
                return this.operationRevisionField;
            }
            set
            {
                this.operationRevisionField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 10)]
        public string dcGroupSequence
        {
            get
            {
                return this.dcGroupSequenceField;
            }
            set
            {
                this.dcGroupSequenceField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 11)]
        public string user
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }

        /// <remarks/>
        [XmlElement("parametricDataArray", Form = XmlSchemaForm.Unqualified, Order = 12)]
        public machineIntegrationParametricData[] parametricDataArray
        {
            get
            {
                return this.parametricDataArrayField;
            }
            set
            {
                this.parametricDataArrayField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace = "http://machine.ws.atlmes.com/")]
    public partial class dataCollectForResourceFAI
    {

        private dataCollectForResourceFAIRequest resourceRequestField;

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 0)]
        public dataCollectForResourceFAIRequest resourceRequest
        {
            get
            {
                return this.resourceRequestField;
            }
            set
            {
                this.resourceRequestField = value;
            }
        }
    }

    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [ServiceContract(Namespace = "http://machine.ws.atlmes.com/", ConfigurationName = "DataCollectForResourceFAIService")]
    public interface DataCollectForModuleTestService
    {

        [OperationContract(Action = "", ReplyAction = "*")]
        [XmlSerializerFormat(SupportFaults = true)]
        [ServiceKnownType(typeof(getCustomDataValueExResponse))]
        [ServiceKnownType(typeof(getCustomDataValueEx))]
        [ServiceKnownType(typeof(baseObject))]
        Task<dataCollectForResourceFAIResponse1> dataCollectForResourceFAIAsync(dataCollectForResourceFAIRequest1 request);

        [OperationContract(Action = "", ReplyAction = "*")]
        [FaultContract(typeof(BusinessException), Action = "", Name = "BusinessException")]
        [XmlSerializerFormat(SupportFaults = true)]
        [ServiceKnownType(typeof(getCustomDataValueExResponse))]
        [ServiceKnownType(typeof(getCustomDataValueEx))]
        [ServiceKnownType(typeof(baseObject))]
        Task<erroAvoidResponse1> erroAvoidAsync(erroAvoidRequest request);

        [OperationContract(Action = "", ReplyAction = "*")]
        [FaultContract(typeof(BusinessException), Action = "", Name = "BusinessException")]
        [XmlSerializerFormat(SupportFaults = true)]
        [ServiceKnownType(typeof(getCustomDataValueExResponse))]
        [ServiceKnownType(typeof(getCustomDataValueEx))]
        [ServiceKnownType(typeof(baseObject))]
        Task<getCustomDataValueExResponse1> getCustomDataValueExAsync(getCustomDataValueExRequest request);
    }

    [DebuggerStepThrough()]
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    [MessageContract(IsWrapped = false)]
    public partial class dataCollectForResourceFAIRequest1
    {

        [MessageBodyMember(Namespace = "http://machine.ws.atlmes.com/", Order = 0)]
        public dataCollectForResourceFAI dataCollectForResourceFAI;

        public dataCollectForResourceFAIRequest1()
        {
        }

        public dataCollectForResourceFAIRequest1(dataCollectForResourceFAI dataCollectForResourceFAI)
        {
            this.dataCollectForResourceFAI = dataCollectForResourceFAI;
        }
    }

    [DebuggerStepThrough()]
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    [MessageContract(IsWrapped = false)]
    public partial class dataCollectForResourceFAIResponse1
    {

        [MessageBodyMember(Namespace = "http://machine.ws.atlmes.com/", Order = 0)]
        public dataCollectForResourceFAIResponse dataCollectForResourceFAIResponse;

        public dataCollectForResourceFAIResponse1()
        {
        }

        public dataCollectForResourceFAIResponse1(dataCollectForResourceFAIResponse dataCollectForResourceFAIResponse)
        {
            this.dataCollectForResourceFAIResponse = dataCollectForResourceFAIResponse;
        }
    }

    [DebuggerStepThrough()]
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    [MessageContract(IsWrapped = false)]
    public partial class erroAvoidRequest
    {

        [MessageBodyMember(Namespace = "http://machine.ws.atlmes.com/", Order = 0)]
        public erroAvoid erroAvoid;

        public erroAvoidRequest()
        {
        }

        public erroAvoidRequest(erroAvoid erroAvoid)
        {
            this.erroAvoid = erroAvoid;
        }
    }

    [DebuggerStepThrough()]
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    [MessageContract(IsWrapped = false)]
    public partial class erroAvoidResponse1
    {

        [MessageBodyMember(Namespace = "http://machine.ws.atlmes.com/", Order = 0)]
        public erroAvoidResponse erroAvoidResponse;

        public erroAvoidResponse1()
        {
        }

        public erroAvoidResponse1(erroAvoidResponse erroAvoidResponse)
        {
            this.erroAvoidResponse = erroAvoidResponse;
        }
    }

    [DebuggerStepThrough()]
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    [MessageContract(IsWrapped = false)]
    public partial class getCustomDataValueExRequest
    {

        [MessageBodyMember(Namespace = "http://machine.ws.atlmes.com/", Order = 0)]
        public getCustomDataValueEx getCustomDataValueEx;

        public getCustomDataValueExRequest()
        {
        }

        public getCustomDataValueExRequest(getCustomDataValueEx getCustomDataValueEx)
        {
            this.getCustomDataValueEx = getCustomDataValueEx;
        }
    }

    [DebuggerStepThrough()]
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    [MessageContract(IsWrapped = false)]
    public partial class getCustomDataValueExResponse1
    {

        [MessageBodyMember(Namespace = "http://machine.ws.atlmes.com/", Order = 0)]
        public getCustomDataValueExResponse getCustomDataValueExResponse;

        public getCustomDataValueExResponse1()
        {
        }

        public getCustomDataValueExResponse1(getCustomDataValueExResponse getCustomDataValueExResponse)
        {
            this.getCustomDataValueExResponse = getCustomDataValueExResponse;
        }
    }

    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface DataCollectForResourceFAIServiceChannel : DataCollectForModuleTestService, IClientChannel
    {
    }

    [DebuggerStepThrough()]
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class DataCollectForResourceFAIServiceClient : ClientBase<DataCollectForModuleTestService>, DataCollectForModuleTestService
    {

        /// <summary>
        /// 实现此分部方法，配置服务终结点。
        /// </summary>
        /// <param name="serviceEndpoint">要配置的终结点</param>
        /// <param name="clientCredentials">客户端凭据</param>
        static partial void ConfigureEndpoint(ServiceEndpoint serviceEndpoint, ClientCredentials clientCredentials);

        public DataCollectForResourceFAIServiceClient() :
                base(GetDefaultBinding(), GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.DataCollectForResourceFAIServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public DataCollectForResourceFAIServiceClient(EndpointConfiguration endpointConfiguration) :
                base(GetBindingForEndpoint(endpointConfiguration), GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public DataCollectForResourceFAIServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(GetBindingForEndpoint(endpointConfiguration), new EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public DataCollectForResourceFAIServiceClient(EndpointConfiguration endpointConfiguration, EndpointAddress remoteAddress) :
                base(GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public DataCollectForResourceFAIServiceClient(Binding binding, EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        Task<dataCollectForResourceFAIResponse1> DataCollectForModuleTestService.dataCollectForResourceFAIAsync(dataCollectForResourceFAIRequest1 request)
        {
            return base.Channel.dataCollectForResourceFAIAsync(request);
        }

        public Task<dataCollectForResourceFAIResponse1> dataCollectForResourceFAIAsync(dataCollectForResourceFAI dataCollectForResourceFAI)
        {
            dataCollectForResourceFAIRequest1 inValue = new dataCollectForResourceFAIRequest1();
            inValue.dataCollectForResourceFAI = dataCollectForResourceFAI;
            return ((DataCollectForModuleTestService)(this)).dataCollectForResourceFAIAsync(inValue);
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        Task<erroAvoidResponse1> DataCollectForModuleTestService.erroAvoidAsync(erroAvoidRequest request)
        {
            return base.Channel.erroAvoidAsync(request);
        }

        public Task<erroAvoidResponse1> erroAvoidAsync(erroAvoid erroAvoid)
        {
            erroAvoidRequest inValue = new erroAvoidRequest();
            inValue.erroAvoid = erroAvoid;
            return ((DataCollectForModuleTestService)(this)).erroAvoidAsync(inValue);
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        Task<getCustomDataValueExResponse1> DataCollectForModuleTestService.getCustomDataValueExAsync(getCustomDataValueExRequest request)
        {
            return base.Channel.getCustomDataValueExAsync(request);
        }

        public Task<getCustomDataValueExResponse1> getCustomDataValueExAsync(getCustomDataValueEx getCustomDataValueEx)
        {
            getCustomDataValueExRequest inValue = new getCustomDataValueExRequest();
            inValue.getCustomDataValueEx = getCustomDataValueEx;
            return ((DataCollectForModuleTestService)(this)).getCustomDataValueExAsync(inValue);
        }

        public virtual Task OpenAsync()
        {
            return Task.Factory.FromAsync(((ICommunicationObject)(this)).BeginOpen(null, null), new Action<IAsyncResult>(((ICommunicationObject)(this)).EndOpen));
        }

        public virtual Task CloseAsync()
        {
            return Task.Factory.FromAsync(((ICommunicationObject)(this)).BeginClose(null, null), new Action<IAsyncResult>(((ICommunicationObject)(this)).EndClose));
        }

        private static Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DataCollectForResourceFAIServicePort))
            {
                BasicHttpBinding result = new BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }

        private static EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DataCollectForResourceFAIServicePort))
            {
                return new EndpointAddress("http://ndmesd093.catlbattery.com:50000/atlmeswebservice/DataCollectForResourceFAI" +
                                           "ServiceService");
            }
            throw new InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }

        private static Binding GetDefaultBinding()
        {
            return GetBindingForEndpoint(EndpointConfiguration.DataCollectForResourceFAIServicePort);
        }

        private static EndpointAddress GetDefaultEndpointAddress()
        {
            return GetEndpointAddress(EndpointConfiguration.DataCollectForResourceFAIServicePort);
        }

        public enum EndpointConfiguration
        {

            DataCollectForResourceFAIServicePort,
        }
    }

}
