//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
//     代码重新生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catl.WebServices.DataCollectForResourceInspect
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://datacollectforresourceinspect.ws.atlmes.com/", ConfigurationName="DataCollectForResourceInspectTaskServiceService.DataCollectForResourceInspectTask" +
        "Service")]
    public interface DataCollectForResourceInspectTaskService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResponse))]
        System.Threading.Tasks.Task<Catl.WebServices.DataCollectForResourceInspect.dataCollectForResourceInspectTaskResponse1> dataCollectForResourceInspectTaskAsync(Catl.WebServices.DataCollectForResourceInspect.dataCollectForResourceInspectTaskRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datacollectforresourceinspect.ws.atlmes.com/")]
    public partial class dataCollectForResourceInspectTask
    {
        
        private dataCollectForResourceInspectTaskRequest dataCollectForResourceInspectTaskRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public dataCollectForResourceInspectTaskRequest DataCollectForResourceInspectTaskRequest
        {
            get
            {
                return this.dataCollectForResourceInspectTaskRequestField;
            }
            set
            {
                this.dataCollectForResourceInspectTaskRequestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datacollectforresourceinspect.ws.atlmes.com/")]
    public partial class dataCollectForResourceInspectTaskRequest
    {
        
        private string siteField;
        
        private string userField;
        
        private string dcModeField;
        
        private string executeModeField;
        
        private string resourceField;
        
        private string operationField;
        
        private string operationRevisionField;
        
        private string dcGroupField;
        
        private string dcGroupRevisionField;
        
        private string dcSequenceField;
        
        private machineIntegrationParametricData[] parametricDataArrayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string site
        {
            get
            {
                return this.siteField;
            }
            set
            {
                this.siteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string user
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string dcMode
        {
            get
            {
                return this.dcModeField;
            }
            set
            {
                this.dcModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string executeMode
        {
            get
            {
                return this.executeModeField;
            }
            set
            {
                this.executeModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string resource
        {
            get
            {
                return this.resourceField;
            }
            set
            {
                this.resourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string operation
        {
            get
            {
                return this.operationField;
            }
            set
            {
                this.operationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string operationRevision
        {
            get
            {
                return this.operationRevisionField;
            }
            set
            {
                this.operationRevisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string dcGroup
        {
            get
            {
                return this.dcGroupField;
            }
            set
            {
                this.dcGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string dcGroupRevision
        {
            get
            {
                return this.dcGroupRevisionField;
            }
            set
            {
                this.dcGroupRevisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string dcSequence
        {
            get
            {
                return this.dcSequenceField;
            }
            set
            {
                this.dcSequenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parametricDataArray", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public machineIntegrationParametricData[] parametricDataArray
        {
            get
            {
                return this.parametricDataArrayField;
            }
            set
            {
                this.parametricDataArrayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datacollectforresourceinspect.ws.atlmes.com/")]
    public partial class machineIntegrationParametricData
    {
        
        private string nameField;
        
        private string valueField;
        
        private ParameterDataType dataTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ParameterDataType dataType
        {
            get
            {
                return this.dataTypeField;
            }
            set
            {
                this.dataTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sap.com/me/datacollection")]
    public enum ParameterDataType
    {
        
        /// <remarks/>
        NUMBER,
        
        /// <remarks/>
        TEXT,
        
        /// <remarks/>
        FORMULA,
        
        /// <remarks/>
        BOOLEAN,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(planOfDataCollectForInspectionResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datacollectforresourceinspect.ws.atlmes.com/")]
    public partial class baseResponse
    {
        
        private int codeField;
        
        private bool codeFieldSpecified;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codeSpecified
        {
            get
            {
                return this.codeFieldSpecified;
            }
            set
            {
                this.codeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datacollectforresourceinspect.ws.atlmes.com/")]
    public partial class planOfDataCollectForInspectionResponse : baseResponse
    {
        
        private int errorCodeField;
        
        private bool errorCodeFieldSpecified;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool errorCodeSpecified
        {
            get
            {
                return this.errorCodeFieldSpecified;
            }
            set
            {
                this.errorCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://datacollectforresourceinspect.ws.atlmes.com/")]
    public partial class dataCollectForResourceInspectTaskResponse
    {
        
        private planOfDataCollectForInspectionResponse returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public planOfDataCollectForInspectionResponse @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class dataCollectForResourceInspectTaskRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://datacollectforresourceinspect.ws.atlmes.com/", Order=0)]
        public Catl.WebServices.DataCollectForResourceInspect.dataCollectForResourceInspectTask dataCollectForResourceInspectTask;
        
        public dataCollectForResourceInspectTaskRequest1()
        {
        }
        
        public dataCollectForResourceInspectTaskRequest1(Catl.WebServices.DataCollectForResourceInspect.dataCollectForResourceInspectTask dataCollectForResourceInspectTask)
        {
            this.dataCollectForResourceInspectTask = dataCollectForResourceInspectTask;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class dataCollectForResourceInspectTaskResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://datacollectforresourceinspect.ws.atlmes.com/", Order=0)]
        public Catl.WebServices.DataCollectForResourceInspect.dataCollectForResourceInspectTaskResponse dataCollectForResourceInspectTaskResponse;
        
        public dataCollectForResourceInspectTaskResponse1()
        {
        }
        
        public dataCollectForResourceInspectTaskResponse1(Catl.WebServices.DataCollectForResourceInspect.dataCollectForResourceInspectTaskResponse dataCollectForResourceInspectTaskResponse)
        {
            this.dataCollectForResourceInspectTaskResponse = dataCollectForResourceInspectTaskResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface DataCollectForResourceInspectTaskServiceChannel : Catl.WebServices.DataCollectForResourceInspect.DataCollectForResourceInspectTaskService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class DataCollectForResourceInspectTaskServiceClient : System.ServiceModel.ClientBase<Catl.WebServices.DataCollectForResourceInspect.DataCollectForResourceInspectTaskService>, Catl.WebServices.DataCollectForResourceInspect.DataCollectForResourceInspectTaskService
    {
        
        /// <summary>
        /// 实现此分部方法，配置服务终结点。
        /// </summary>
        /// <param name="serviceEndpoint">要配置的终结点</param>
        /// <param name="clientCredentials">客户端凭据</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DataCollectForResourceInspectTaskServiceClient() : 
                base(DataCollectForResourceInspectTaskServiceClient.GetDefaultBinding(), DataCollectForResourceInspectTaskServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.DataCollectForResourceInspectTaskServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataCollectForResourceInspectTaskServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(DataCollectForResourceInspectTaskServiceClient.GetBindingForEndpoint(endpointConfiguration), DataCollectForResourceInspectTaskServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataCollectForResourceInspectTaskServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DataCollectForResourceInspectTaskServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataCollectForResourceInspectTaskServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DataCollectForResourceInspectTaskServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataCollectForResourceInspectTaskServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Catl.WebServices.DataCollectForResourceInspect.dataCollectForResourceInspectTaskResponse1> Catl.WebServices.DataCollectForResourceInspect.DataCollectForResourceInspectTaskService.dataCollectForResourceInspectTaskAsync(Catl.WebServices.DataCollectForResourceInspect.dataCollectForResourceInspectTaskRequest1 request)
        {
            return base.Channel.dataCollectForResourceInspectTaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<Catl.WebServices.DataCollectForResourceInspect.dataCollectForResourceInspectTaskResponse1> dataCollectForResourceInspectTaskAsync(Catl.WebServices.DataCollectForResourceInspect.dataCollectForResourceInspectTask dataCollectForResourceInspectTask)
        {
            Catl.WebServices.DataCollectForResourceInspect.dataCollectForResourceInspectTaskRequest1 inValue = new Catl.WebServices.DataCollectForResourceInspect.dataCollectForResourceInspectTaskRequest1();
            inValue.dataCollectForResourceInspectTask = dataCollectForResourceInspectTask;
            return ((Catl.WebServices.DataCollectForResourceInspect.DataCollectForResourceInspectTaskService)(this)).dataCollectForResourceInspectTaskAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DataCollectForResourceInspectTaskServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DataCollectForResourceInspectTaskServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://zzmes1p024.catlbattery.com:50400/atlmeswebservice/DataCollectForResourceIn" +
                        "spectTaskServiceService");
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return DataCollectForResourceInspectTaskServiceClient.GetBindingForEndpoint(EndpointConfiguration.DataCollectForResourceInspectTaskServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return DataCollectForResourceInspectTaskServiceClient.GetEndpointAddress(EndpointConfiguration.DataCollectForResourceInspectTaskServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            DataCollectForResourceInspectTaskServicePort,
        }
    }
}
