namespace Catl.WebServices.MiAssembleComponentsToSfcs
{
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
//     代码重新生成。
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://machineintegration.ws.atlmes.com/", ConfigurationName="MiAssembleComponentsToSfcsService")]
public interface MiAssembleComponentsToSfcsService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<miAssembleComponentsToSfcsResponse1> miAssembleComponentsToSfcsAsync(miAssembleComponentsToSfcsRequest request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
public partial class miAssembleComponentsToSfcs
{
    
    private assembleComponentsToSfcsRequest assembleComponentsToSfcsRequestField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public assembleComponentsToSfcsRequest AssembleComponentsToSfcsRequest
    {
        get
        {
            return this.assembleComponentsToSfcsRequestField;
        }
        set
        {
            this.assembleComponentsToSfcsRequestField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
public partial class assembleComponentsToSfcsRequest
{
    
    private string siteField;
    
    private string operationField;
    
    private string operationRevField;
    
    private string resourceField;
    
    private string userField;
    
    private string activityField;
    
    private string amountField;
    
    private assembleData[] assembleDataArrayField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string site
    {
        get
        {
            return this.siteField;
        }
        set
        {
            this.siteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string operation
    {
        get
        {
            return this.operationField;
        }
        set
        {
            this.operationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public string operationRev
    {
        get
        {
            return this.operationRevField;
        }
        set
        {
            this.operationRevField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public string resource
    {
        get
        {
            return this.resourceField;
        }
        set
        {
            this.resourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
    public string user
    {
        get
        {
            return this.userField;
        }
        set
        {
            this.userField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
    public string activity
    {
        get
        {
            return this.activityField;
        }
        set
        {
            this.activityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
    public string amount
    {
        get
        {
            return this.amountField;
        }
        set
        {
            this.amountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("assembleDataArray", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
    public assembleData[] assembleDataArray
    {
        get
        {
            return this.assembleDataArrayField;
        }
        set
        {
            this.assembleDataArrayField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
public partial class assembleData
{
    
    private string sfcField;
    
    private inventoryData[] inventoryArrayField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string sfc
    {
        get
        {
            return this.sfcField;
        }
        set
        {
            this.sfcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("inventoryArray", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public inventoryData[] inventoryArray
    {
        get
        {
            return this.inventoryArrayField;
        }
        set
        {
            this.inventoryArrayField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
public partial class inventoryData
{
    
    private string inventoryField;
    
    private string qtyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string inventory
    {
        get
        {
            return this.inventoryField;
        }
        set
        {
            this.inventoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string qty
    {
        get
        {
            return this.qtyField;
        }
        set
        {
            this.qtyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
public partial class assembleComponentsToSfcsResponse
{
    
    private int codeField;
    
    private bool codeFieldSpecified;
    
    private string messageField;
    
    private int failedLocationField;
    
    private bool failedLocationFieldSpecified;
    
    private string failedSfcField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public int code
    {
        get
        {
            return this.codeField;
        }
        set
        {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool codeSpecified
    {
        get
        {
            return this.codeFieldSpecified;
        }
        set
        {
            this.codeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string message
    {
        get
        {
            return this.messageField;
        }
        set
        {
            this.messageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
    public int failedLocation
    {
        get
        {
            return this.failedLocationField;
        }
        set
        {
            this.failedLocationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool failedLocationSpecified
    {
        get
        {
            return this.failedLocationFieldSpecified;
        }
        set
        {
            this.failedLocationFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
    public string failedSfc
    {
        get
        {
            return this.failedSfcField;
        }
        set
        {
            this.failedSfcField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
public partial class miAssembleComponentsToSfcsResponse
{
    
    private assembleComponentsToSfcsResponse returnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public assembleComponentsToSfcsResponse @return
    {
        get
        {
            return this.returnField;
        }
        set
        {
            this.returnField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class miAssembleComponentsToSfcsRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://machineintegration.ws.atlmes.com/", Order=0)]
    public miAssembleComponentsToSfcs miAssembleComponentsToSfcs;
    
    public miAssembleComponentsToSfcsRequest()
    {
    }
    
    public miAssembleComponentsToSfcsRequest(miAssembleComponentsToSfcs miAssembleComponentsToSfcs)
    {
        this.miAssembleComponentsToSfcs = miAssembleComponentsToSfcs;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class miAssembleComponentsToSfcsResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://machineintegration.ws.atlmes.com/", Order=0)]
    public miAssembleComponentsToSfcsResponse miAssembleComponentsToSfcsResponse;
    
    public miAssembleComponentsToSfcsResponse1()
    {
    }
    
    public miAssembleComponentsToSfcsResponse1(miAssembleComponentsToSfcsResponse miAssembleComponentsToSfcsResponse)
    {
        this.miAssembleComponentsToSfcsResponse = miAssembleComponentsToSfcsResponse;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
public interface MiAssembleComponentsToSfcsServiceChannel : MiAssembleComponentsToSfcsService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
public partial class MiAssembleComponentsToSfcsServiceClient : System.ServiceModel.ClientBase<MiAssembleComponentsToSfcsService>, MiAssembleComponentsToSfcsService
{
    
    /// <summary>
    /// 实现此分部方法，配置服务终结点。
    /// </summary>
    /// <param name="serviceEndpoint">要配置的终结点</param>
    /// <param name="clientCredentials">客户端凭据</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
    
    public MiAssembleComponentsToSfcsServiceClient() : 
            base(MiAssembleComponentsToSfcsServiceClient.GetDefaultBinding(), MiAssembleComponentsToSfcsServiceClient.GetDefaultEndpointAddress())
    {
        this.Endpoint.Name = EndpointConfiguration.MiAssembleComponentsToSfcsServicePort.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public MiAssembleComponentsToSfcsServiceClient(EndpointConfiguration endpointConfiguration) : 
            base(MiAssembleComponentsToSfcsServiceClient.GetBindingForEndpoint(endpointConfiguration), MiAssembleComponentsToSfcsServiceClient.GetEndpointAddress(endpointConfiguration))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public MiAssembleComponentsToSfcsServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
            base(MiAssembleComponentsToSfcsServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public MiAssembleComponentsToSfcsServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(MiAssembleComponentsToSfcsServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public MiAssembleComponentsToSfcsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<miAssembleComponentsToSfcsResponse1> MiAssembleComponentsToSfcsService.miAssembleComponentsToSfcsAsync(miAssembleComponentsToSfcsRequest request)
    {
        return base.Channel.miAssembleComponentsToSfcsAsync(request);
    }
    
    public System.Threading.Tasks.Task<miAssembleComponentsToSfcsResponse1> miAssembleComponentsToSfcsAsync(miAssembleComponentsToSfcs miAssembleComponentsToSfcs)
    {
        miAssembleComponentsToSfcsRequest inValue = new miAssembleComponentsToSfcsRequest();
        inValue.miAssembleComponentsToSfcs = miAssembleComponentsToSfcs;
        return ((MiAssembleComponentsToSfcsService)(this)).miAssembleComponentsToSfcsAsync(inValue);
    }
    
    public virtual System.Threading.Tasks.Task OpenAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }
    
    public virtual System.Threading.Tasks.Task CloseAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
    }
    
    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.MiAssembleComponentsToSfcsServicePort))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            return result;
        }
        throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
    }
    
    private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.MiAssembleComponentsToSfcsServicePort))
        {
            return new System.ServiceModel.EndpointAddress("http://lymesap226.catlbattery.com:50300/atlmeswebservice/MiAssembleComponentsToSf" +
                    "csServiceService");
        }
        throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
    }
    
    private static System.ServiceModel.Channels.Binding GetDefaultBinding()
    {
        return MiAssembleComponentsToSfcsServiceClient.GetBindingForEndpoint(EndpointConfiguration.MiAssembleComponentsToSfcsServicePort);
    }
    
    private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
    {
        return MiAssembleComponentsToSfcsServiceClient.GetEndpointAddress(EndpointConfiguration.MiAssembleComponentsToSfcsServicePort);
    }
    
    public enum EndpointConfiguration
    {
        
        MiAssembleComponentsToSfcsServicePort,
    }
}

}
