using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.ServiceModel;
using System.ServiceModel.Channels;
using System.ServiceModel.Description;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Schema;
using System.Xml.Serialization;

namespace Catl.WebServices.MiAssembleComponentsToSfcs
{
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
//     代码重新生成。
// </auto-generated>
//------------------------------------------------------------------------------



[GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[ServiceContract(Namespace="http://machineintegration.ws.atlmes.com/", ConfigurationName="MiAssembleComponentsToSfcsService")]
public interface MiAssembleComponentsToSfcsService
{
    
    [OperationContract(Action="", ReplyAction="*")]
    [XmlSerializerFormat(SupportFaults=true)]
    Task<miAssembleComponentsToSfcsResponse1> miAssembleComponentsToSfcsAsync(miAssembleComponentsToSfcsRequest request);
}

/// <remarks/>
[GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[DebuggerStepThrough()]
[XmlType(Namespace="http://machineintegration.ws.atlmes.com/")]
public partial class miAssembleComponentsToSfcs
{
    
    private assembleComponentsToSfcsRequest assembleComponentsToSfcsRequestField;
    
    /// <remarks/>
    [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
    public assembleComponentsToSfcsRequest AssembleComponentsToSfcsRequest
    {
        get
        {
            return this.assembleComponentsToSfcsRequestField;
        }
        set
        {
            this.assembleComponentsToSfcsRequestField = value;
        }
    }
}

/// <remarks/>
[GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[DebuggerStepThrough()]
[XmlType(Namespace="http://machineintegration.ws.atlmes.com/")]
public partial class assembleComponentsToSfcsRequest
{
    
    private string siteField;
    
    private string operationField;
    
    private string operationRevField;
    
    private string resourceField;
    
    private string userField;
    
    private string activityField;
    
    private string amountField;
    
    private assembleData[] assembleDataArrayField;
    
    /// <remarks/>
    [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
    public string site
    {
        get
        {
            return this.siteField;
        }
        set
        {
            this.siteField = value;
        }
    }
    
    /// <remarks/>
    [XmlElement(Form=XmlSchemaForm.Unqualified, Order=1)]
    public string operation
    {
        get
        {
            return this.operationField;
        }
        set
        {
            this.operationField = value;
        }
    }
    
    /// <remarks/>
    [XmlElement(Form=XmlSchemaForm.Unqualified, Order=2)]
    public string operationRev
    {
        get
        {
            return this.operationRevField;
        }
        set
        {
            this.operationRevField = value;
        }
    }
    
    /// <remarks/>
    [XmlElement(Form=XmlSchemaForm.Unqualified, Order=3)]
    public string resource
    {
        get
        {
            return this.resourceField;
        }
        set
        {
            this.resourceField = value;
        }
    }
    
    /// <remarks/>
    [XmlElement(Form=XmlSchemaForm.Unqualified, Order=4)]
    public string user
    {
        get
        {
            return this.userField;
        }
        set
        {
            this.userField = value;
        }
    }
    
    /// <remarks/>
    [XmlElement(Form=XmlSchemaForm.Unqualified, Order=5)]
    public string activity
    {
        get
        {
            return this.activityField;
        }
        set
        {
            this.activityField = value;
        }
    }
    
    /// <remarks/>
    [XmlElement(Form=XmlSchemaForm.Unqualified, Order=6)]
    public string amount
    {
        get
        {
            return this.amountField;
        }
        set
        {
            this.amountField = value;
        }
    }
    
    /// <remarks/>
    [XmlElement("assembleDataArray", Form=XmlSchemaForm.Unqualified, Order=7)]
    public assembleData[] assembleDataArray
    {
        get
        {
            return this.assembleDataArrayField;
        }
        set
        {
            this.assembleDataArrayField = value;
        }
    }
}

/// <remarks/>
[GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[DebuggerStepThrough()]
[XmlType(Namespace="http://machineintegration.ws.atlmes.com/")]
public partial class assembleData
{
    
    private string sfcField;
    
    private inventoryData[] inventoryArrayField;
    
    /// <remarks/>
    [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
    public string sfc
    {
        get
        {
            return this.sfcField;
        }
        set
        {
            this.sfcField = value;
        }
    }
    
    /// <remarks/>
    [XmlElement("inventoryArray", Form=XmlSchemaForm.Unqualified, Order=1)]
    public inventoryData[] inventoryArray
    {
        get
        {
            return this.inventoryArrayField;
        }
        set
        {
            this.inventoryArrayField = value;
        }
    }
}

/// <remarks/>
[GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[DebuggerStepThrough()]
[XmlType(Namespace="http://machineintegration.ws.atlmes.com/")]
public partial class inventoryData
{
    
    private string inventoryField;
    
    private string qtyField;
    
    /// <remarks/>
    [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
    public string inventory
    {
        get
        {
            return this.inventoryField;
        }
        set
        {
            this.inventoryField = value;
        }
    }
    
    /// <remarks/>
    [XmlElement(Form=XmlSchemaForm.Unqualified, Order=1)]
    public string qty
    {
        get
        {
            return this.qtyField;
        }
        set
        {
            this.qtyField = value;
        }
    }
}

/// <remarks/>
[GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[DebuggerStepThrough()]
[XmlType(Namespace="http://machineintegration.ws.atlmes.com/")]
public partial class assembleComponentsToSfcsResponse
{
    
    private int codeField;
    
    private bool codeFieldSpecified;
    
    private string messageField;
    
    private int failedLocationField;
    
    private bool failedLocationFieldSpecified;
    
    private string failedSfcField;
    
    /// <remarks/>
    [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
    public int code
    {
        get
        {
            return this.codeField;
        }
        set
        {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    [XmlIgnore()]
    public bool codeSpecified
    {
        get
        {
            return this.codeFieldSpecified;
        }
        set
        {
            this.codeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [XmlElement(Form=XmlSchemaForm.Unqualified, Order=1)]
    public string message
    {
        get
        {
            return this.messageField;
        }
        set
        {
            this.messageField = value;
        }
    }
    
    /// <remarks/>
    [XmlElement(Form=XmlSchemaForm.Unqualified, Order=2)]
    public int failedLocation
    {
        get
        {
            return this.failedLocationField;
        }
        set
        {
            this.failedLocationField = value;
        }
    }
    
    /// <remarks/>
    [XmlIgnore()]
    public bool failedLocationSpecified
    {
        get
        {
            return this.failedLocationFieldSpecified;
        }
        set
        {
            this.failedLocationFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [XmlElement(Form=XmlSchemaForm.Unqualified, Order=3)]
    public string failedSfc
    {
        get
        {
            return this.failedSfcField;
        }
        set
        {
            this.failedSfcField = value;
        }
    }
}

/// <remarks/>
[GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[DebuggerStepThrough()]
[XmlType(Namespace="http://machineintegration.ws.atlmes.com/")]
public partial class miAssembleComponentsToSfcsResponse
{
    
    private assembleComponentsToSfcsResponse returnField;
    
    /// <remarks/>
    [XmlElement(Form=XmlSchemaForm.Unqualified, Order=0)]
    public assembleComponentsToSfcsResponse @return
    {
        get
        {
            return this.returnField;
        }
        set
        {
            this.returnField = value;
        }
    }
}

[DebuggerStepThrough()]
[GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[EditorBrowsable(EditorBrowsableState.Advanced)]
[MessageContract(IsWrapped=false)]
public partial class miAssembleComponentsToSfcsRequest
{
    
    [MessageBodyMember(Namespace="http://machineintegration.ws.atlmes.com/", Order=0)]
    public miAssembleComponentsToSfcs miAssembleComponentsToSfcs;
    
    public miAssembleComponentsToSfcsRequest()
    {
    }
    
    public miAssembleComponentsToSfcsRequest(miAssembleComponentsToSfcs miAssembleComponentsToSfcs)
    {
        this.miAssembleComponentsToSfcs = miAssembleComponentsToSfcs;
    }
}

[DebuggerStepThrough()]
[GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[EditorBrowsable(EditorBrowsableState.Advanced)]
[MessageContract(IsWrapped=false)]
public partial class miAssembleComponentsToSfcsResponse1
{
    
    [MessageBodyMember(Namespace="http://machineintegration.ws.atlmes.com/", Order=0)]
    public miAssembleComponentsToSfcsResponse miAssembleComponentsToSfcsResponse;
    
    public miAssembleComponentsToSfcsResponse1()
    {
    }
    
    public miAssembleComponentsToSfcsResponse1(miAssembleComponentsToSfcsResponse miAssembleComponentsToSfcsResponse)
    {
        this.miAssembleComponentsToSfcsResponse = miAssembleComponentsToSfcsResponse;
    }
}

[GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
public interface MiAssembleComponentsToSfcsServiceChannel : MiAssembleComponentsToSfcsService, IClientChannel
{
}

[DebuggerStepThrough()]
[GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
public partial class MiAssembleComponentsToSfcsServiceClient : ClientBase<MiAssembleComponentsToSfcsService>, MiAssembleComponentsToSfcsService
{
    
    /// <summary>
    /// 实现此分部方法，配置服务终结点。
    /// </summary>
    /// <param name="serviceEndpoint">要配置的终结点</param>
    /// <param name="clientCredentials">客户端凭据</param>
    static partial void ConfigureEndpoint(ServiceEndpoint serviceEndpoint, ClientCredentials clientCredentials);
    
    public MiAssembleComponentsToSfcsServiceClient() : 
            base(GetDefaultBinding(), GetDefaultEndpointAddress())
    {
        this.Endpoint.Name = EndpointConfiguration.MiAssembleComponentsToSfcsServicePort.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public MiAssembleComponentsToSfcsServiceClient(EndpointConfiguration endpointConfiguration) : 
            base(GetBindingForEndpoint(endpointConfiguration), GetEndpointAddress(endpointConfiguration))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public MiAssembleComponentsToSfcsServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
            base(GetBindingForEndpoint(endpointConfiguration), new EndpointAddress(remoteAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public MiAssembleComponentsToSfcsServiceClient(EndpointConfiguration endpointConfiguration, EndpointAddress remoteAddress) : 
            base(GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public MiAssembleComponentsToSfcsServiceClient(Binding binding, EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    Task<miAssembleComponentsToSfcsResponse1> MiAssembleComponentsToSfcsService.miAssembleComponentsToSfcsAsync(miAssembleComponentsToSfcsRequest request)
    {
        return base.Channel.miAssembleComponentsToSfcsAsync(request);
    }
    
    public Task<miAssembleComponentsToSfcsResponse1> miAssembleComponentsToSfcsAsync(miAssembleComponentsToSfcs miAssembleComponentsToSfcs)
    {
        miAssembleComponentsToSfcsRequest inValue = new miAssembleComponentsToSfcsRequest();
        inValue.miAssembleComponentsToSfcs = miAssembleComponentsToSfcs;
        return ((MiAssembleComponentsToSfcsService)(this)).miAssembleComponentsToSfcsAsync(inValue);
    }
    
    public virtual Task OpenAsync()
    {
        return Task.Factory.FromAsync(((ICommunicationObject)(this)).BeginOpen(null, null), new Action<IAsyncResult>(((ICommunicationObject)(this)).EndOpen));
    }
    
    public virtual Task CloseAsync()
    {
        return Task.Factory.FromAsync(((ICommunicationObject)(this)).BeginClose(null, null), new Action<IAsyncResult>(((ICommunicationObject)(this)).EndClose));
    }
    
    private static Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.MiAssembleComponentsToSfcsServicePort))
        {
            BasicHttpBinding result = new BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            return result;
        }
        throw new InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
    }
    
    private static EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.MiAssembleComponentsToSfcsServicePort))
        {
            return new EndpointAddress("http://lymesap226.catlbattery.com:50300/atlmeswebservice/MiAssembleComponentsToSf" +
                                       "csServiceService");
        }
        throw new InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
    }
    
    private static Binding GetDefaultBinding()
    {
        return GetBindingForEndpoint(EndpointConfiguration.MiAssembleComponentsToSfcsServicePort);
    }
    
    private static EndpointAddress GetDefaultEndpointAddress()
    {
        return GetEndpointAddress(EndpointConfiguration.MiAssembleComponentsToSfcsServicePort);
    }
    
    public enum EndpointConfiguration
    {
        
        MiAssembleComponentsToSfcsServicePort,
    }
}

}
