using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.ServiceModel;
using System.ServiceModel.Channels;
using System.ServiceModel.Description;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Schema;
using System.Xml.Serialization;

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Catl.WebServices.MICheckBOMInventory
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     此代码由工具生成。
    //
    //     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
    //     代码重新生成。
    // </auto-generated>
    //------------------------------------------------------------------------------



    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [ServiceContract(Namespace = "http://machineintegration.ws.atlmes.com/", ConfigurationName = "MiCheckBOMInventoryService")]
    public interface MiCheckBOMInventoryService
    {

        [OperationContract(Action = "", ReplyAction = "*")]
        [XmlSerializerFormat(SupportFaults = true)]
        Task<miCheckBOMInventoryResponse1> miCheckBOMInventoryAsync(miCheckBOMInventoryRequest request);
    }

    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace = "http://machineintegration.ws.atlmes.com/")]
    public partial class miCheckBOMInventory
    {

        private checkBOMInventoryRequest checkBOMInventoryRequestField;

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 0)]
        public checkBOMInventoryRequest CheckBOMInventoryRequest
        {
            get
            {
                return this.checkBOMInventoryRequestField;
            }
            set
            {
                this.checkBOMInventoryRequestField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace = "http://machineintegration.ws.atlmes.com/")]
    public partial class checkBOMInventoryRequest
    {

        private string siteField;

        private string operationField;

        private string operationRevisionField;

        private string resourceField;

        private customData[] customDataArrayField;

        private string userField;

        private string activityField;

        private string sfcField;

        private bool modeCheckOperationField;

        private modeProcessSFC modeProcessSFCField;

        private checkBomInventoryData[] inventoryDataArrayField;

        public checkBOMInventoryRequest()
        {
            this.operationRevisionField = "#";
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 0)]
        public string site
        {
            get
            {
                return this.siteField;
            }
            set
            {
                this.siteField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 1)]
        public string operation
        {
            get
            {
                return this.operationField;
            }
            set
            {
                this.operationField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 2)]
        [DefaultValue("#")]
        public string operationRevision
        {
            get
            {
                return this.operationRevisionField;
            }
            set
            {
                this.operationRevisionField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 3)]
        public string resource
        {
            get
            {
                return this.resourceField;
            }
            set
            {
                this.resourceField = value;
            }
        }

        /// <remarks/>
        [XmlElement("customDataArray", Form = XmlSchemaForm.Unqualified, Order = 4)]
        public customData[] customDataArray
        {
            get
            {
                return this.customDataArrayField;
            }
            set
            {
                this.customDataArrayField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 5)]
        public string user
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 6)]
        public string activity
        {
            get
            {
                return this.activityField;
            }
            set
            {
                this.activityField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 7)]
        public string sfc
        {
            get
            {
                return this.sfcField;
            }
            set
            {
                this.sfcField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 8)]
        public bool modeCheckOperation
        {
            get
            {
                return this.modeCheckOperationField;
            }
            set
            {
                this.modeCheckOperationField = value;
            }
        }

        [JsonConverter(typeof(StringEnumConverter))]
        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 9)]
        public modeProcessSFC modeProcessSFC
        {
            get
            {
                return this.modeProcessSFCField;
            }
            set
            {
                this.modeProcessSFCField = value;
            }
        }

        /// <remarks/>
        [XmlElement("inventoryDataArray", Form = XmlSchemaForm.Unqualified, Order = 10)]
        public checkBomInventoryData[] inventoryDataArray
        {
            get
            {
                return this.inventoryDataArrayField;
            }
            set
            {
                this.inventoryDataArrayField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace = "http://machineintegration.ws.atlmes.com/")]
    public partial class customData
    {

        private string usageField;

        private ObjectAliasEnum categoryField;

        private string dataFieldField;

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 0)]
        public string usage
        {
            get
            {
                return this.usageField;
            }
            set
            {
                this.usageField = value;
            }
        }

        [JsonConverter(typeof(StringEnumConverter))]

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 1)]
        public ObjectAliasEnum category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 2)]
        public string dataField
        {
            get
            {
                return this.dataFieldField;
            }
            set
            {
                this.dataFieldField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [XmlType(Namespace = "http://www.sap.com/me/common")]
    public enum ObjectAliasEnum
    {

        /// <remarks/>
        ACTIVITY,

        /// <remarks/>
        ACTIVITY_GROUP,

        /// <remarks/>
        ACTIVITY_LOG,

        /// <remarks/>
        ALARM,

        /// <remarks/>
        ALARM_LOG,

        /// <remarks/>
        APPLICATION_SETTING,

        /// <remarks/>
        ATTACHMENT,

        /// <remarks/>
        ATTENDANCE_LOG,

        /// <remarks/>
        BACKGROUND_PROCESS,

        /// <remarks/>
        BOM,

        /// <remarks/>
        BOM_COMPONENT,

        /// <remarks/>
        BUYOFF,

        /// <remarks/>
        BUYOFF_LOG,

        /// <remarks/>
        CERTIFICATION,

        /// <remarks/>
        CNC_PROGRAM,

        /// <remarks/>
        CONTAINER,

        /// <remarks/>
        CONTAINER_DATA,

        /// <remarks/>
        COST_CENTER,

        /// <remarks/>
        CUSTOMER,

        /// <remarks/>
        DATA_FIELD,

        /// <remarks/>
        DATA_TYPE,

        /// <remarks/>
        DC_GROUP,

        /// <remarks/>
        DOCUMENT,

        /// <remarks/>
        INVENTORY,

        /// <remarks/>
        INVENTORY_LOG,

        /// <remarks/>
        ITEM_GROUP,

        /// <remarks/>
        LABOR_CHARGE_CODE,

        /// <remarks/>
        MESSAGE,

        /// <remarks/>
        MESSAGE_LOG,

        /// <remarks/>
        MESSAGE_TYPE,

        /// <remarks/>
        NC_CODE,

        /// <remarks/>
        NEXT_NUMBER,

        /// <remarks/>
        OPERATION,

        /// <remarks/>
        PROCESS_LOT,

        /// <remarks/>
        PRODUCTION_LOG,

        /// <remarks/>
        REASON_CODE,

        /// <remarks/>
        SAMPLE_PLAN,

        /// <remarks/>
        WORK_INSTRUCTION,

        /// <remarks/>
        ITEM,

        /// <remarks/>
        RESOURCE,

        /// <remarks/>
        ROUTER,

        /// <remarks/>
        SHOP_ORDER,

        /// <remarks/>
        ROUTER_STEP,

        /// <remarks/>
        ROUTER_OPERATION,

        /// <remarks/>
        SFC,

        /// <remarks/>
        USR,

        /// <remarks/>
        USER_GROUP,

        /// <remarks/>
        WORK_CENTER,

        /// <remarks/>
        WORKSTATION,

        /// <remarks/>
        RESOURCE_TYPE,

        /// <remarks/>
        CUSTOMER_ORDER,
    }

    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace = "http://machineintegration.ws.atlmes.com/")]
    public partial class checkBOMInventoryResponse
    {

        private int codeField;

        private bool codeFieldSpecified;

        private string messageField;

        private string failedInventoryField;

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 0)]
        public int code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool codeSpecified
        {
            get
            {
                return this.codeFieldSpecified;
            }
            set
            {
                this.codeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 1)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 2)]
        public string failedInventory
        {
            get
            {
                return this.failedInventoryField;
            }
            set
            {
                this.failedInventoryField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace = "http://machineintegration.ws.atlmes.com/")]
    public partial class miCheckBOMInventoryResponse
    {

        private checkBOMInventoryResponse returnField;

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 0)]
        public checkBOMInventoryResponse @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace = "http://machineintegration.ws.atlmes.com/")]
    public partial class checkBomInventoryData
    {

        private string inventoryField;

        private string componentField;

        private string qtyField;

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 0)]
        public string inventory
        {
            get
            {
                return this.inventoryField;
            }
            set
            {
                this.inventoryField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 1)]
        public string component
        {
            get
            {
                return this.componentField;
            }
            set
            {
                this.componentField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 2)]
        public string qty
        {
            get
            {
                return this.qtyField;
            }
            set
            {
                this.qtyField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [XmlType(Namespace = "http://machineintegration.ws.atlmes.com/")]
    public enum modeProcessSFC
    {

        /// <remarks/>
        MODE_NONE,

        /// <remarks/>
        MODE_START_SFC,

        /// <remarks/>
        MODE_COMPLETE_SFC,

        /// <remarks/>
        MODE_PASS_SFC,

        /// <remarks/>
        MODE_START_COMPLETE_SFC,
    }

    [DebuggerStepThrough()]
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    [MessageContract(IsWrapped = false)]
    public partial class miCheckBOMInventoryRequest
    {

        [MessageBodyMember(Namespace = "http://machineintegration.ws.atlmes.com/", Order = 0)]
        public miCheckBOMInventory miCheckBOMInventory;

        public miCheckBOMInventoryRequest()
        {
        }

        public miCheckBOMInventoryRequest(miCheckBOMInventory miCheckBOMInventory)
        {
            this.miCheckBOMInventory = miCheckBOMInventory;
        }
    }

    [DebuggerStepThrough()]
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    [MessageContract(IsWrapped = false)]
    public partial class miCheckBOMInventoryResponse1
    {

        [MessageBodyMember(Namespace = "http://machineintegration.ws.atlmes.com/", Order = 0)]
        public miCheckBOMInventoryResponse miCheckBOMInventoryResponse;

        public miCheckBOMInventoryResponse1()
        {
        }

        public miCheckBOMInventoryResponse1(miCheckBOMInventoryResponse miCheckBOMInventoryResponse)
        {
            this.miCheckBOMInventoryResponse = miCheckBOMInventoryResponse;
        }
    }

    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface MiCheckBOMInventoryServiceChannel : MiCheckBOMInventoryService, IClientChannel
    {
    }

    [DebuggerStepThrough()]
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class MiCheckBOMInventoryServiceClient : ClientBase<MiCheckBOMInventoryService>, MiCheckBOMInventoryService
    {

        /// <summary>
        /// 实现此分部方法，配置服务终结点。
        /// </summary>
        /// <param name="serviceEndpoint">要配置的终结点</param>
        /// <param name="clientCredentials">客户端凭据</param>
        static partial void ConfigureEndpoint(ServiceEndpoint serviceEndpoint, ClientCredentials clientCredentials);

        public MiCheckBOMInventoryServiceClient() :
                base(GetDefaultBinding(), GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.MiCheckBOMInventoryServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public MiCheckBOMInventoryServiceClient(EndpointConfiguration endpointConfiguration) :
                base(GetBindingForEndpoint(endpointConfiguration), GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public MiCheckBOMInventoryServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(GetBindingForEndpoint(endpointConfiguration), new EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public MiCheckBOMInventoryServiceClient(EndpointConfiguration endpointConfiguration, EndpointAddress remoteAddress) :
                base(GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public MiCheckBOMInventoryServiceClient(Binding binding, EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        Task<miCheckBOMInventoryResponse1> MiCheckBOMInventoryService.miCheckBOMInventoryAsync(miCheckBOMInventoryRequest request)
        {
            return base.Channel.miCheckBOMInventoryAsync(request);
        }

        public Task<miCheckBOMInventoryResponse1> miCheckBOMInventoryAsync(miCheckBOMInventory miCheckBOMInventory)
        {
            miCheckBOMInventoryRequest inValue = new miCheckBOMInventoryRequest();
            inValue.miCheckBOMInventory = miCheckBOMInventory;
            return ((MiCheckBOMInventoryService)(this)).miCheckBOMInventoryAsync(inValue);
        }

        public virtual Task OpenAsync()
        {
            return Task.Factory.FromAsync(((ICommunicationObject)(this)).BeginOpen(null, null), new Action<IAsyncResult>(((ICommunicationObject)(this)).EndOpen));
        }

        public virtual Task CloseAsync()
        {
            return Task.Factory.FromAsync(((ICommunicationObject)(this)).BeginClose(null, null), new Action<IAsyncResult>(((ICommunicationObject)(this)).EndClose));
        }

        private static Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MiCheckBOMInventoryServicePort))
            {
                BasicHttpBinding result = new BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }

        private static EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MiCheckBOMInventoryServicePort))
            {
                return new EndpointAddress("http://ndmesd093.catlbattery.com:50000/atlmeswebservice/MiCheckBOMInventoryServic" +
                                           "eService");
            }
            throw new InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }

        private static Binding GetDefaultBinding()
        {
            return GetBindingForEndpoint(EndpointConfiguration.MiCheckBOMInventoryServicePort);
        }

        private static EndpointAddress GetDefaultEndpointAddress()
        {
            return GetEndpointAddress(EndpointConfiguration.MiCheckBOMInventoryServicePort);
        }

        public enum EndpointConfiguration
        {

            MiCheckBOMInventoryServicePort,
        }
    }

}
