
namespace Catl.WebServices.MICheckSFCStatusEx
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     此代码由工具生成。
    //
    //     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
    //     代码重新生成。
    // </auto-generated>
    //------------------------------------------------------------------------------



    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://machineintegration.ws.atlmes.com/", ConfigurationName = "MiCheckSFCStatusExService")]
    public interface MiCheckSFCStatusExService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<miCheckSFCStatusExResponse1> miCheckSFCStatusExAsync(miCheckSFCStatusExRequest request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://machineintegration.ws.atlmes.com/")]
    public partial class miCheckSFCStatusEx
    {

        private changeSFCStatusExRequest changeSFCStatusExRequestField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public changeSFCStatusExRequest ChangeSFCStatusExRequest
        {
            get
            {
                return this.changeSFCStatusExRequestField;
            }
            set
            {
                this.changeSFCStatusExRequestField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://machineintegration.ws.atlmes.com/")]
    public partial class changeSFCStatusExRequest
    {

        private string siteField;

        private string operationField;

        private string operationRevisionField;

        private string sfcField;

        private string isGetSFCFromCustomerBarcodeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string site
        {
            get
            {
                return this.siteField;
            }
            set
            {
                this.siteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string operation
        {
            get
            {
                return this.operationField;
            }
            set
            {
                this.operationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string operationRevision
        {
            get
            {
                return this.operationRevisionField;
            }
            set
            {
                this.operationRevisionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string sfc
        {
            get
            {
                return this.sfcField;
            }
            set
            {
                this.sfcField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string isGetSFCFromCustomerBarcode
        {
            get
            {
                return this.isGetSFCFromCustomerBarcodeField;
            }
            set
            {
                this.isGetSFCFromCustomerBarcodeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://machineintegration.ws.atlmes.com/")]
    public partial class miCommonResponse
    {

        private int codeField;

        private bool codeFieldSpecified;

        private string messageField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public int code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codeSpecified
        {
            get
            {
                return this.codeFieldSpecified;
            }
            set
            {
                this.codeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://machineintegration.ws.atlmes.com/")]
    public partial class miCheckSFCStatusExResponse
    {

        private miCommonResponse returnField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public miCommonResponse @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class miCheckSFCStatusExRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://machineintegration.ws.atlmes.com/", Order = 0)]
        public miCheckSFCStatusEx miCheckSFCStatusEx;

        public miCheckSFCStatusExRequest()
        {
        }

        public miCheckSFCStatusExRequest(miCheckSFCStatusEx miCheckSFCStatusEx)
        {
            this.miCheckSFCStatusEx = miCheckSFCStatusEx;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class miCheckSFCStatusExResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://machineintegration.ws.atlmes.com/", Order = 0)]
        public miCheckSFCStatusExResponse miCheckSFCStatusExResponse;

        public miCheckSFCStatusExResponse1()
        {
        }

        public miCheckSFCStatusExResponse1(miCheckSFCStatusExResponse miCheckSFCStatusExResponse)
        {
            this.miCheckSFCStatusExResponse = miCheckSFCStatusExResponse;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface MiCheckSFCStatusExServiceChannel : MiCheckSFCStatusExService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class MiCheckSFCStatusExServiceClient : System.ServiceModel.ClientBase<MiCheckSFCStatusExService>, MiCheckSFCStatusExService
    {

        /// <summary>
        /// 实现此分部方法，配置服务终结点。
        /// </summary>
        /// <param name="serviceEndpoint">要配置的终结点</param>
        /// <param name="clientCredentials">客户端凭据</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public MiCheckSFCStatusExServiceClient() :
                base(MiCheckSFCStatusExServiceClient.GetDefaultBinding(), MiCheckSFCStatusExServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.MiCheckSFCStatusExServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public MiCheckSFCStatusExServiceClient(EndpointConfiguration endpointConfiguration) :
                base(MiCheckSFCStatusExServiceClient.GetBindingForEndpoint(endpointConfiguration), MiCheckSFCStatusExServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public MiCheckSFCStatusExServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(MiCheckSFCStatusExServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public MiCheckSFCStatusExServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(MiCheckSFCStatusExServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public MiCheckSFCStatusExServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<miCheckSFCStatusExResponse1> MiCheckSFCStatusExService.miCheckSFCStatusExAsync(miCheckSFCStatusExRequest request)
        {
            return base.Channel.miCheckSFCStatusExAsync(request);
        }

        public System.Threading.Tasks.Task<miCheckSFCStatusExResponse1> miCheckSFCStatusExAsync(miCheckSFCStatusEx miCheckSFCStatusEx)
        {
            miCheckSFCStatusExRequest inValue = new miCheckSFCStatusExRequest();
            inValue.miCheckSFCStatusEx = miCheckSFCStatusEx;
            return ((MiCheckSFCStatusExService)(this)).miCheckSFCStatusExAsync(inValue);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MiCheckSFCStatusExServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MiCheckSFCStatusExServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://ndmesd093.catlbattery.com:50000/atlmeswebservice/MiCheckSFCStatusExService" +
                        "Service");
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MiCheckSFCStatusExServiceClient.GetBindingForEndpoint(EndpointConfiguration.MiCheckSFCStatusExServicePort);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MiCheckSFCStatusExServiceClient.GetEndpointAddress(EndpointConfiguration.MiCheckSFCStatusExServicePort);
        }

        public enum EndpointConfiguration
        {

            MiCheckSFCStatusExServicePort,
        }
    }

}
