
using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.ServiceModel;
using System.ServiceModel.Channels;
using System.ServiceModel.Description;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Schema;
using System.Xml.Serialization;

namespace Catl.WebServices.MICheckSFCStatusEx
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     此代码由工具生成。
    //
    //     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
    //     代码重新生成。
    // </auto-generated>
    //------------------------------------------------------------------------------



    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [ServiceContract(Namespace = "http://machineintegration.ws.atlmes.com/", ConfigurationName = "MiCheckSFCStatusExService")]
    public interface MiCheckSFCStatusExService
    {

        [OperationContract(Action = "", ReplyAction = "*")]
        [XmlSerializerFormat(SupportFaults = true)]
        Task<miCheckSFCStatusExResponse1> miCheckSFCStatusExAsync(miCheckSFCStatusExRequest request);
    }

    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace = "http://machineintegration.ws.atlmes.com/")]
    public partial class miCheckSFCStatusEx
    {

        private changeSFCStatusExRequest changeSFCStatusExRequestField;

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 0)]
        public changeSFCStatusExRequest ChangeSFCStatusExRequest
        {
            get
            {
                return this.changeSFCStatusExRequestField;
            }
            set
            {
                this.changeSFCStatusExRequestField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace = "http://machineintegration.ws.atlmes.com/")]
    public partial class changeSFCStatusExRequest
    {

        private string siteField;

        private string operationField;

        private string operationRevisionField;

        private string sfcField;

        private string isGetSFCFromCustomerBarcodeField;

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 0)]
        public string site
        {
            get
            {
                return this.siteField;
            }
            set
            {
                this.siteField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 1)]
        public string operation
        {
            get
            {
                return this.operationField;
            }
            set
            {
                this.operationField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 2)]
        public string operationRevision
        {
            get
            {
                return this.operationRevisionField;
            }
            set
            {
                this.operationRevisionField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 3)]
        public string sfc
        {
            get
            {
                return this.sfcField;
            }
            set
            {
                this.sfcField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 4)]
        public string isGetSFCFromCustomerBarcode
        {
            get
            {
                return this.isGetSFCFromCustomerBarcodeField;
            }
            set
            {
                this.isGetSFCFromCustomerBarcodeField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace = "http://machineintegration.ws.atlmes.com/")]
    public partial class miCommonResponse
    {

        private int codeField;

        private bool codeFieldSpecified;

        private string messageField;

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 0)]
        public int code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool codeSpecified
        {
            get
            {
                return this.codeFieldSpecified;
            }
            set
            {
                this.codeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 1)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }

    /// <remarks/>
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [DebuggerStepThrough()]
    [XmlType(Namespace = "http://machineintegration.ws.atlmes.com/")]
    public partial class miCheckSFCStatusExResponse
    {

        private miCommonResponse returnField;

        /// <remarks/>
        [XmlElement(Form = XmlSchemaForm.Unqualified, Order = 0)]
        public miCommonResponse @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }

    [DebuggerStepThrough()]
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    [MessageContract(IsWrapped = false)]
    public partial class miCheckSFCStatusExRequest
    {

        [MessageBodyMember(Namespace = "http://machineintegration.ws.atlmes.com/", Order = 0)]
        public miCheckSFCStatusEx miCheckSFCStatusEx;

        public miCheckSFCStatusExRequest()
        {
        }

        public miCheckSFCStatusExRequest(miCheckSFCStatusEx miCheckSFCStatusEx)
        {
            this.miCheckSFCStatusEx = miCheckSFCStatusEx;
        }
    }

    [DebuggerStepThrough()]
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    [MessageContract(IsWrapped = false)]
    public partial class miCheckSFCStatusExResponse1
    {

        [MessageBodyMember(Namespace = "http://machineintegration.ws.atlmes.com/", Order = 0)]
        public miCheckSFCStatusExResponse miCheckSFCStatusExResponse;

        public miCheckSFCStatusExResponse1()
        {
        }

        public miCheckSFCStatusExResponse1(miCheckSFCStatusExResponse miCheckSFCStatusExResponse)
        {
            this.miCheckSFCStatusExResponse = miCheckSFCStatusExResponse;
        }
    }

    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface MiCheckSFCStatusExServiceChannel : MiCheckSFCStatusExService, IClientChannel
    {
    }

    [DebuggerStepThrough()]
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class MiCheckSFCStatusExServiceClient : ClientBase<MiCheckSFCStatusExService>, MiCheckSFCStatusExService
    {

        /// <summary>
        /// 实现此分部方法，配置服务终结点。
        /// </summary>
        /// <param name="serviceEndpoint">要配置的终结点</param>
        /// <param name="clientCredentials">客户端凭据</param>
        static partial void ConfigureEndpoint(ServiceEndpoint serviceEndpoint, ClientCredentials clientCredentials);

        public MiCheckSFCStatusExServiceClient() :
                base(GetDefaultBinding(), GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.MiCheckSFCStatusExServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public MiCheckSFCStatusExServiceClient(EndpointConfiguration endpointConfiguration) :
                base(GetBindingForEndpoint(endpointConfiguration), GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public MiCheckSFCStatusExServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(GetBindingForEndpoint(endpointConfiguration), new EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public MiCheckSFCStatusExServiceClient(EndpointConfiguration endpointConfiguration, EndpointAddress remoteAddress) :
                base(GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public MiCheckSFCStatusExServiceClient(Binding binding, EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        Task<miCheckSFCStatusExResponse1> MiCheckSFCStatusExService.miCheckSFCStatusExAsync(miCheckSFCStatusExRequest request)
        {
            return base.Channel.miCheckSFCStatusExAsync(request);
        }

        public Task<miCheckSFCStatusExResponse1> miCheckSFCStatusExAsync(miCheckSFCStatusEx miCheckSFCStatusEx)
        {
            miCheckSFCStatusExRequest inValue = new miCheckSFCStatusExRequest();
            inValue.miCheckSFCStatusEx = miCheckSFCStatusEx;
            return ((MiCheckSFCStatusExService)(this)).miCheckSFCStatusExAsync(inValue);
        }

        public virtual Task OpenAsync()
        {
            return Task.Factory.FromAsync(((ICommunicationObject)(this)).BeginOpen(null, null), new Action<IAsyncResult>(((ICommunicationObject)(this)).EndOpen));
        }

        public virtual Task CloseAsync()
        {
            return Task.Factory.FromAsync(((ICommunicationObject)(this)).BeginClose(null, null), new Action<IAsyncResult>(((ICommunicationObject)(this)).EndClose));
        }

        private static Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MiCheckSFCStatusExServicePort))
            {
                BasicHttpBinding result = new BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }

        private static EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MiCheckSFCStatusExServicePort))
            {
                return new EndpointAddress("http://ndmesd093.catlbattery.com:50000/atlmeswebservice/MiCheckSFCStatusExService" +
                                           "Service");
            }
            throw new InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }

        private static Binding GetDefaultBinding()
        {
            return GetBindingForEndpoint(EndpointConfiguration.MiCheckSFCStatusExServicePort);
        }

        private static EndpointAddress GetDefaultEndpointAddress()
        {
            return GetEndpointAddress(EndpointConfiguration.MiCheckSFCStatusExServicePort);
        }

        public enum EndpointConfiguration
        {

            MiCheckSFCStatusExServicePort,
        }
    }

}
