# GCCS_POSITION_OFFSET = 640
# for i in range(10):
#     print(GCCS_POSITION_OFFSET + i * 4)

NJJG_POSITION_OFFSET = 680
for i in range(30):
    print(NJJG_POSITION_OFFSET)
    NJJG_POSITION_OFFSET += 2
    print(NJJG_POSITION_OFFSET)
    NJJG_POSITION_OFFSET += 2
    print(NJJG_POSITION_OFFSET)
    NJJG_POSITION_OFFSET += 2
    print(NJJG_POSITION_OFFSET)
    NJJG_POSITION_OFFSET += 4
    print(NJJG_POSITION_OFFSET)
    NJJG_POSITION_OFFSET += 4